---
title: "El Sistema Producto Barbacoa de Capulhuac como manifestación del capitaloceno y la economía circular"
author:
  - name: "Omar Miranda-Gómez"
    affiliation: "Universidad Autónoma Metropolitana, unidad Lerma"
    orcid: ""
    email: "o_miranda@correo.ler.uam.mx"
  - name: "Ignacio López Moreno"
    affiliation: "Universidad Autónoma Metropolitana, unidad Lerma"
    orcid: "0000-0002-0900-3473"
    email: "i.lopez@correo.ler.uam.mx"
chapter-number: 1
page-range: ""
doi: ""
resumen: |
  Capulhuac en el Estado de México, es un municipio productor de barbacoa que oferta en distintos puntos del altiplano central del país. Aunque su demanda promueve un desarrollo regional al emplear gran cantidad de familias, esta actividad impacta negativamente al ambiente. El objetivo consiste en analizar esta actividad en el contexto del capitaloceno y los desafíos y oportunidades que se cuentan para promover modelos de economía circular. El estudio parte del trabajo de campo enfocado en el sistema producto barbacoa, considerando una serie de análisis cualitativos y cuantitativos que permiten identificar el cambio socio-territorial en la región. Entre los resultados, se encontró que la demanda de barbacoa en la región central de México ha generado una serie de impactos ambientales en Capulhuac asociado con la noción de capitaloceno pero existen estrategias que pueden mitigar dicha problemática mediante la implementación de modelos de economía circular.
keywords:
  - "capitaloceno"
  - "Capulhuac"
  - "Medio Ambiente"
type: chapter
---

\addtocontents{toc}{\protect\hspace{1.5em}Omar Miranda-Gómez e Ignacio López Moreno\par}
\markboth{El Sistema Producto Barbacoa de Capulhuac como manifestación del capitaloceno}{}

\begin{flushright}
\Large Omar Miranda-Gómez \footnote{ Contacto: \href{mailto:o\_miranda@correo.ler.uam.mx }{o\_miranda@correo.ler.uam.mx}} \\
\Large Ignacio López Moreno \footnote{ Contacto: \href{mailto:i.lopez@correo.ler.uam.mx }{i.lopez@correo.ler.uam.mx}}
\end{flushright}

## Introducción {.unlisted .unnumbered}

> _El pecado mayor del ambientalismo, el conjunto de movimientos en defensa de la naturaleza y sus autores, fue habernos hecho creer que los culpables de la destrucción del mundo natural éramos todos los seres humanos sin excepción_
> 
> > Víctor Toledo (2019)

Según @Ulloa2019, el capitaloceno no solo se refiere a las acciones humanas directas sobre el medio ambiente, sino también a la apropiación de la naturaleza y los territorios como parte de las valoraciones económicas capitalistas. En el contexto actual, caracterizado por un profundo deterioro ambiental, la economía circular se presenta como una alternativa al modelo lineal capitalista tradicional, que explota y agota los recursos naturales. Sin embargo, el capitalismo impera en muchas de las dinámicas económicas y ambientales. El objetivo de este artículo es analizar los desafíos y oportunidades de la economía circular en el contexto del capitaloceno, destacando cómo las dinámicas económicas capitalistas influyen en las transformaciones territoriales. Para ello, se contextualiza la evolución del municipio de Capulhuac, un antiguo territorio rural lacustre que se ha consolidado como el principal centro de producción de barbacoa en México, como un ejemplo emblemático de las interacciones entre el capitalismo y las crisis socioambientales globales.

Capulhuac, en el Estado de México es un territorio de fundación matlatzinca de aproximadamente 600 años de antigüedad. En 2020, contaba con una población de 36,921 habitantes de los cuales, el 48.15% son hombres y el 51.85% mujeres  [@INEGI2020]. Este municipio ha experimentado un crecimiento poblacional constante, lo que ha fomentado una demanda de bienes, servicios y de trabajo por parte de esta población. Según datos del ayuntamiento, unas 4 mil familias procesan aproximadamente 15 mil cabezas de ganado ovino a la semana. Su cambio ha sido paulatino y poco a poco ha transformado la vida cotidiana y las prácticas de todas las familias del municipio. Su origen está en tres elementos fundamentales: los saberes y relaciones que las familias arrieras de la comunidad adquirieron durante el primer tercio del siglo anterior; los cambios acontecidos en su ambiente por la canalización de las lagunas del Alto Lerma por orden del Gobierno Federal en 1942; y el crecimiento exponencial de la población de la cercana Ciudad de México como una megalópolis moderna insaciable en su demandan de comida.

El documento se estructura en cinco partes. En primer lugar, se habla sobre el origen de la barbacoa y su importancia económica en el municipio. Después, se expone cómo es que el proceso de transformación socioeconómica se orienta a lógicas capitalistas que fomentan un desarrollo poco sustentable de su entorno. Seguido de ello, se habla sobre la economía circular en el contexto del capitaloceno. Posteriormente, se discuten los elementos más relevantes que permiten la transformación de este territorio, asociados a la implementación de una economía circular y se exponen una serie de retos y futuras líneas de investigación derivadas del proceso analítico. Por último, se enuncian algunas consideraciones finales derivadas de este proceso de reflexión.

## La barbacoa: Un platillo de impacto regional en Capulhuac {.unlisted .unnumbered}

La gastronomía mexicana ha sido considerada un regalo para el mundo, pues desde la época prehispánica la preparación culinaria de los alimentos era distinta a la conocida por los habitantes del continente europeo. Los antiguos pueblos se alimentaban principalmente de frutas, calabazas, frijol, chile y maíz, de este último se hacían distintos tipos de tortillas, tamales, varias especies de aves, conejos, venados, liebres, armadillos, peces, ranas, ajolotes, hormigas, gusanos de maguey, tomaban atoles, chocolate y pulque, [@DeSahagun1540a: 297-310]. La preparación de la carne se podía hacer a través del asado a fuego directo de la misma, su cocimiento al vapor, guisada con chiles, tomates o pepitas, y por supuesto se asaba bajo la tierra en un horno subterráneo (barbacoa) [@DeSahagun1540b: 55; @Iturriaga2013: 13].

Los estudios de diferentes disciplinas sobre el origen de la palabra barbacoa nos hablan de un posible origen maya, _Baalbak’Kaab_ (carne tapada con tierra), y otro caribeño, _Barabicu_ (carne cocinada sobre andamios de madera) [@CiddelPrado2021]. Más allá de dichas teorías, la barbacoa y sus diferentes variedades coinciden en el uso del calor indirecto para cocinar, siendo el lugar un espacio cavado en el suelo, en el que se coloca leña que posteriormente se rodea o cubre con piedras. Una vez consumida la leña se añade la carne con los avíos que se consideran adecuados, y se tapan usando hojas de plátano o maguey. Finalmente, la carne y los elementos que se hayan usado son extraídos y presentados según la tradición del lugar.

Inicialmente, se utilizaba carne de fauna nativa, pero a la llegada de los europeos se introdujeron distintos animales, como puercos, caballos, vacas, borregos y cabras. Lo que dio pauta a una expansión ganadera en la zona centro del país, debido a que estos territorios contaban con condiciones favorables para alimentar a dichos herbívoros [@Cedillo1999: 24-26]. Como resultado de este mestizaje, se dio paso al cambio en la gastronomía pues la carne traída del viejo mundo pudo ser preparada bajo diversas técnicas culinarias prehispánicas.

Hoy en día, encontramos que en México existen tres variables principales de barbacoa según su proceso: de hoyo, hervida y de horno. La primera es la que más se parece a la práctica original, y es muy apreciada por el sabor especial que el calor de las piedras y los rescoldos de la leña dan, aunque genera menor cantidad de caldo de carne o consomé. Según las entrevistas levantadas durante el trabajo de campo, esta es una de las principales razones, junto a las enfermedades respiratorias que provoca, para la introducción de la técnica de hervido o cocimiento en olla. Esta técnica está muy extendida en Capulhuac, ya que al ser un pueblo hojalatero antes de desarrollar su industria de la barbacoa, resulta relativamente fácil conseguir artesanos que fabriquen los aperos a medida. En esta segunda modalidad se usan grandes ollas de acero inoxidable, y en el fondo de esta, coronada por una estructura que sostiene la carne, suele ubicarse otra olla que recogerá el jugo del cocimiento. Finalmente, el horno es una variante menos extendida, pero que mezcla el resultado de las dos, al permitir usar gas o leña e incorporar olla para recoger el máximo caldo y conseguir a la vez un sabor especial.

La barbacoa preparada actualmente en Capulhuac es producto muy diverso, tanto en la forma de preparación, ya que la cocinan en las tres formas ya descritas, como por el desarrollo de recetas familiares que la hacen similar pero diferentes entre sí. Si lo miramos desde un punto de vista medioambiental, la llegada y expansión de este producto en el municipio vino a raíz del proceso de desecación de las Ciénagas de Lerma, pues desde su fundación el municipio era un pueblo que vivía de las bondades de los productos lacustres, de la agricultura y del maguey [@Pillado2013].

Como resultado de la rica y compleja cultura del agua los pobladores pudieron, por aproximadamente cuatro siglos, aprovechar los productos brindados por la laguna (pescado, ajolotes, ranas, aves, vegetales y tule), los cuales fueron el sustento alimenticio y económico de la zona hasta mediados del siglo pasado, cuando en 1942 se realizó el proceso de Canalización de las lagunas del Alto Lerma por orden federal. Desde entonces las principales actividades que sustituyeron a las lacustres son: el comercio, labores en la industria y agricultura, es decir, la forma de subsistencia se basó en estas nuevas actividades [@Ceballos2003]. En resumen, tal y como lo demostraron ¶Pillado et al. (2013, (p. 63), fueron principalmente cinco los factores que favorecieron la comercialización de la barbacoa como principal actividad económica de Capulhuac: 

> 1) la necesidad de sustituir las mercancías lacustres que antiguamente vendían para su sustento, 2) la disponibilidad de ganado lanar en los pueblos vecinos, 3) las rutas de comercio hacia el Valle de México, Tierra Caliente y los pueblos de montaña del Alto Lerma, 4) abundancia de magueyes en la región y 5) la costumbre de vender productos lacustres guisados en los mercados de la región.

Según las historias de vida que tuvimos la oportunidad de levantar fueron las familias Pulido y Zamora las que comenzaron a producir y comercializar barbacoa en la Ciudad de México a final de los años cuarenta. Uno de los rasgos principales de este sistema producto es la división sexual y generacional propio de la economía campesina. Esta forma organizacional, como veremos más adelante, transitó de la vida y lógica económica del campesinado a un sistema productivo basado en el oficio, lo que también le dio una forma particular de producir y reproducirse.

El sistema productivo basado en el oficio tiene su principal fortaleza en la patrimonialidad, lo que significa heredar el derecho de dominio formando una secuencia de obligaciones entre generaciones. No se trata de pasar un saber frío y técnico, sino de un conjunto de saber hacer que forman parte de la cultura del trabajo propia del sistema y que genera formas de vida específicas. En este sentido, hablamos de unas prácticas y conocimientos que se consideran de gran valor dentro de las familias, y cuya transmisión se hace de manera cuidad y selectiva, siendo sobre todo entre generaciones diferentes. Por lo tanto, es un marco institucional que incluye normas, saberes y habilidades que permiten la reproducción social de las familias, y por ende, del sistema-producto.

Aunado a los cambios territoriales del municipio antes comentados, en las décadas de los sesenta y setenta el ambulantismo de los barbacoeros comenzó a ser institucionalizado y regulado con la entrada de una nueva generación surgida entre los ayudantes de los dueños que iniciaron sus actividades veinte años atrás [@Pillado2013]. La formalización de la oferta estuvo acompañada de un fuerte aumento en la demanda de insumos, lo que conllevó la aparición de industrias centradas en subproductos, como las curtidurías, que se proveían de las pieles de borregos y cabras. Incluso hoy en día, la venta de las pieles supone una entrada importante para las familias barbacoera, siendo sus principales destinos San Mateo Atenco (Estado de México) y León (Guanajuato)  [@Garcia1999a].

Siguiendo este recorrido histórico “desde 1970 hasta 2019 la producción de carne de ovino tuvo un crecimiento sostenido de 2,2% de media anual, de igual modo, el consumo per cápita pasó de 467g a 567g” CONSULTAR [@BobadillaSoto2021: 1]. Si esta información la contrastamos con los siguientes datos, podremos comprender mejor la magnitud del caso que estamos manejando: se consumen unas cien mil toneladas al año, y según diversas investigaciones, entre el 90 y el 95% de esta carne tiene como finalidad la producción de barbacoa [@BobadillaSoto2021; @CiddelPrado2021;  @Isla2020].

En cuanto a la producción ovina a nivel nacional, los estados de México e Hidalgo concentran el 29% de la población ovina, una de las razones por las cuales se le puede atribuir este dato, es porque son lugares que tradicionalmente concentran una gran parte de la producción, el comercio y la transformación de la carne.

Según los datos que hemos podido levantar en nuestro trabajo de campo, en Capulhuac se sacrifican entre 10 y 15 mil borregos semanales, siendo la gran mayoría importados de estados como, Jalisco, Zacatecas y Chihuahua. Este volumen semanal puede ser traducido a 30 mil toneladas al año de borrego vivo, y unas 13 mil en canal. Todo este enorme volumen de carne es procesado por unas 4 mil familias residentes en Capulhuac. En tal sentido, estos números nos hablan de magnitudes que imposibilitan una relación sociedad-naturaleza sustentable, y cuyo impacto se extiende más allá del mismo municipio de Capulhuac a través de las cadenas de importación de bienes necesarios para mantener el sistema. A continuación, se discute el concepto de capitaloceno como un proceso que genera transformaciones ambientales como resultado de lógicas económicas asociadas con el capitalismo.

## El capitaloceno como manifestación de la degradación ambiental en Capulhuac {.unlisted .unnumbered}

Anteriormente se había planteado el concepto de antropoceno para hablar de una fase de grave crisis ecológica global, que consideraba a la humanidad como el principal catalizador de este proceso. Sin embargo, éste presenta críticas como su falta de perspectiva histórica, pues su concepción homogeniza a toda la humanidad, como si todos los seres humanos contribuyeran de igual modo en la creación de los actuales problemas socioecológicos [@Herrero2017].

Como respuesta a esta crítica, se planteó la necesidad de que exista un cambio de estado intelectual que acompañe esta nueva era, pues la etapa geológica conocida como antropoceno resulta problemática [@Moore2018]. Por tal razón, una mejor aproximación de esta realidad sería hablar del capitaloceno.

Según Jason Moore considerado como el creador del término capitaloceno, este proceso se entiende como una era histórica dominada por el capital, y se caracteriza por una transformación radical del medio ambiente en algo denominado economía moderna [@Wedekind2017]. Moore sostiene que esta crisis ambiental comenzó con los inicios del capitalismo de la era moderna (inicios de 1450 en adelante) y, consecuentemente, fue generada por el modo de producción capitalista y los sectores de la sociedad que más se han beneficiado con éste [@Estenssoro2021].

En este sentido, el capitaloceno resalta que no solo las acciones humanas directas dan pauta a las transformaciones ambientales, sino que la apropiación de la naturaleza y los territorios, son producto de valoraciones económicas capitalistas [@Ulloa2019]. “El Capitaloceno se propone como una manera de entender las relaciones con lo no humano en procesos capitalistas, lo que implica considerar 'diferentes escalas, complejidad y el proceso de apropiación de la naturaleza'” [Haraway, 2015 citado en @Ulloa2017: 67]. Una de estas escalas corresponde al ámbito local, como el caso de Capulhuac.

La relación entre Capulhuac y su ambiente ha ido degradándose paulatinamente hacia formas no sustentables por las dinámicas de explotación humana y no humana que caracterizan al capitalismo, especialmente, en los ámbitos de producción y consumo de alimentos, como en muchos otros lugares (González de Molina y Guzmán, 2006).

Su principal actividad económica consiste en la producción y venta de barbacoa en la Ciudad de México y sus alrededores. De las 2025 Unidades Económicas (UE) censadas por el Instituto Nacional de Estadística y Geografía (INEGI), 728 están dedicadas al comercio al por menor, 647 a la preparación de alimentos y bebidas, 188 a la industria manufacturera, y 120 a la industria alimentaria; lo que viene a ser un 83% de las UE censadas en el municipio [@INEGI2015]. Si bien en otros pueblos estas UE podrían centrarse en diversos sectores económicos, en Capulhuac giran en torno a la producción y venta de barbacoa, siendo más de 4,000 familias las que forman parte del sector según el estudio realizado por el CONSULTAR Gobierno Municipal de Capulhuac (2018).

La escala de producción es tan alta que su ambiente próximo no puede generar con suficiente velocidad los bienes requeridos, por lo que se ha convertido en el nudo de una red que tejen todo tipo de cadenas multiescalares. El éxito de la economía de Capulhuac sólo puede ser definida como tal dentro de paradigmas económicos reduccionistas que no tienen en cuenta dimensiones sociales, culturales, políticas, ambientales y emocionales. Las dinámicas de trabajo en este entorno rural están caracterizadas por la informalidad y la auto-explotación familiar con una fuerte inequidad de género [@VizcarraBordi2020], con la llegada de la pandemia de la COVID-19 llevó a la comunidad a una situación límite por su alto nivel de especialización económica y dependencia externa. Por tal razón, Capulhuac debe mirar hacia sí mismo y su ambiente para recuperar formas de interacción más sustentables y alternativas que reduzcan el impacto que tienen sobre sí mismos y su ambiente.

En los últimos años la soberanía alimentaria y la justicia ambiental son temas en auge que afortunadamente han entrado en la agenda social y académica. Estos dos conceptos nos permiten observar y analizar dinámicas producidas por el capitaloceno. El capitaloceno, entendido como la era actual en la que un sistema económico construye la realidad con base en su lógica de apropiación y explotación de la naturaleza y la sociedad, se manifiesta también en los sistemas agroalimentarios. Si bien existen ejemplos de alternativas interesantes, muchos otros muestran las consecuencias de la penetración de la lógica del mercado en nuestros agroecosistemas.

## Economía circular en el contexto del capitaloceno {.unlisted .unnumbered}

La intensificación del sistema capitalista trae consigo amenazas que rebasan las fronteras ecológicas cuyo proceso impacta de manera negativa la biosfera [@Escalera2018]. La relación entre el capitaloceno y la economía circular es compleja, ya que ambos conceptos abordan la interacción entre los sistemas económicos y la sostenibilidad ambiental. Por un lado, e capitaloceno critica el papel del capitalismo en la degradación ecológica, mientras que la economía circular propone un modelo orientado a la eficiencia de los recursos y la sostenibilidad.

El capitaloceno refleja cómo el modelo económico capitalista ha sostenido su crecimiento a través de la explotación intensiva de los recursos naturales. Según @Escalera2018, las lógicas extractivistas del capitalismo han generado una "brecha metabólica", donde el desajuste entre los ciclos naturales y las dinámicas económicas extractivas contribuyen al agotamiento de los recursos, dando como resultado la actual crisis económica y ambiental.

Ante este panorama, la economía circular se plantea como una oportunidad para mitigar el impacto del capitalismo extractivista al promover modelos que reduzcan el deterioro ambiental y diversifiquen las lógicas económicas capitalistas [@ElSaltoDiario2024]. Este modelo, surge como una respuesta a la lógica lineal de "tomar, hacer, desechar", promoviendo la reutilización, el reciclaje y la regeneración de los recursos. Esta estrategia pretende mitigar los impactos ambientales de las actividades productivas y fomentar la ssustentabilidad. Sin embargo, el contexto del capitaloceno y las dinámicas capitalistas pueden limitar su efectividad.

Debemos reconocer que la economía circular se enfoca en reducir los residuos y reutilizar los materiales para crear sistemas de circuito cerrado [@Haas2020]. Su propósito consiste en minimizar la extracción de recursos y el impacto ambiental, promoviendo los beneficios socioeconómicos a través de prácticas sostenibles y relaciones integradas con las partes interesadas [@Casalegno2020].

Al hablar de economía circular y capitaloceno se deben reconocer una serie de Interconexiones y desafíos. Si bien la economía circular ofrece soluciones para mitigar los efectos del capitaloceno, puede resultar insuficiente si no aborda las estructuras capitalistas que perpetúan la degradación ambiental [@Deutz2023]. Por el contrario, algunos sostienen que la economía circular, si bien es beneficiosa, puede reforzar las estructuras capitalistas al centrarse en los patrones de consumo.

Un aspecto clave que limita el potencial de la economía circular, es la cooptación de sus principios por el sistema capitalista. Muchos enfoques de economía circular se ven reducidos a prácticas dentro de los márgenes del sistema económico dominante, lo que genera dudas sobre su capacidad real para transformar las estructuras productivas y sociales. La economía circular podría ser fácilmente absorbida por los intereses capitalistas que buscan mantener el modelo de consumo sin cambiar las estructuras subyacentes [@ElSaltoDiario2024].

Una propuesta para generar una transformación del modelo económico consiste en plantear la necesidad de una transformación profunda que no solo adopte la economía circular, sino que también cuestione el modelo de explotación capitalista. Esto implica repensar los sistemas de producción y consumo, reconociendo que la verdadera sostenibilidad requiere una ruptura con las lógicas extractivistas y una transición hacia un modelo que valore los derechos de la naturaleza y las comunidades CONSULTAR (UAM, 2022).

La transición hacia una economía circular, enfrenta importantes desafíos. Estos desafíos involucran dimensiones tecnológicas, regulatorias, organizativas y socioeconómicas. Las barreras organizacionales incluyen la resistencia al cambio y la necesidad de una transformación sustancial en los modelos de negocio para integrar prácticas circulares [@Gupta2024]. La ambigüedad regulatoria y la falta de alineación dificultan la implementación de las prácticas de economía circular. Se necesitan políticas e incentivos claros para fomentar la inversión y la innovación [@Gupta2024]. En México, las barreras económicas se ven agravadas por insuficiencias regulatorias, que dificultan la adopción de las prácticas de economía circular [@PadillaRivera2024].

Abordar estas barreras implica fomentar la colaboración, alinear políticas e innovar tecnológicamente. No obstante, la transición a una economía circular también se ve obstaculizada por intereses arraigados y dinámicas de poder existentes, que favorecen las prácticas intensivas en recursos sobre las alternativas sustentables.

En este sentido, es oportuno aplicar políticas públicas que no solo promuevan la sostenibilidad, sino que también cuestionen las estructuras económicas de explotación capitalista. Dichas políticas deben estar orientadas hacia la transformación del modelo productivo, lo que incluye el fomento de prácticas como el reciclaje, el diseño ecológico y la educación ambiental [@Escalera2018].

Finalmente, la economía circular debe ir acompañada de un proceso de concienciación colectiva sobre la importancia de cambiar nuestra relación con el medio ambiente. Es necesario impulsar una cultura de consumo responsable y una revalorización de los recursos naturales, que permita no solo la sostenibilidad ecológica, sino también una mayor equidad social.

## Discusión y análisis prospectivo {.unlisted .unnumbered}

El mercado agroalimentario y la gastronomía han cobrado importancia y se ha reconocido como una herramienta de desarrollo capitalista y de generación de rentas elevadas [@VanDerPloeg2010]. Este auge ha sido promovido por una constante innovación organizativa y mercadotécnica que ha permitido generar un alto valor agregado a alimentos que formaban parte de tradiciones locales. Dentro de las estrategias para la generación de valor agregado destacan aquellas que pasan por vincular un producto a un territorio y un imaginario colectivo positivo [@EspeitxBernat1996].

En este sentido, la barbacoa mexicana está estrechamente vinculada a los sistemas de producción ovina, una actividad que ha cobrado notoriedad en los últimos tiempos por un cambio de paradigma en la forma de entender su relación con el medio ambiente y por los altos precios de garantía que ha alcanzado el mercado. Numerosos estudios han demostrado la viabilidad de la actividad en términos de sostenibilidad ambiental, reducción de emisiones de gases de efecto invernadero, pastoreo racional y precios de garantía, comparados con el ganado bovino. Por lo cual, numerosos países están reconvirtiendo gradualmente la producción bovina de carne a ovina, sobre todo en aquellos agroecosistemas, donde los ovinos son más eficientes y tienen menos efectos ambientales. De acuerdo con las últimas estadísticas, en México existe un inventario de 7 millones 82 mil 990 cabezas de ganado ovino, de las cuales el 70.9% se localiza en diez estados de la república y sólo el 29.1% se ubica en las 21 entidades federativas restantes [@PartidadelaPena2013]. La mayor parte de esta producción es consumida a través de la cadena de valor de la barbacoa en las zonas del interior de la república. Tradicionalmente, México ha sido deficitario en la producción de carne de ovina, recurriendo a las importaciones para complementar el abasto debido al gran demanda que tiene este producto [@BobadillaSoto2017], principalmente de países como Australia, Nueva Zelandia, Canadá, Estados Unidos América (EUA) y Uruguay [@MondragonAncelmo2012].

La barbacoa es un alimento con una fuerte carga histórica e identitaria. Su origen es prehispánico, y su consumo solía estar vinculado a rituales o fiestas [@Katz2019a]. Sin embargo, en los últimos años existe una alta demanda debido a la configuración de un consumidor con mayor capacidad de pago, exigente y en busca de barbacoa con calidad organoléptica notable. Por lo cual, su producción y consumo se han diversificado drásticamente. Las innovaciones en su producción han llevado en algunos casos a generar formas industriales que han reducido el coste y aumentado la accesibilidad de este platillo mexicano. Esto puede ser observado fácilmente en el municipio de Capulhuac (Estado de México), donde según lo identificado en campo importan borregos de toda la república y se sacrifican más de 15.000 cabezas ovinas a la semana, más del 10% de la producción ovina nacional.

Otro de los elementos que se relacionan con la idea de capitaloceno, se relaciona con la idea de lo barato. Moore argumenta que la expansión del capitaloceno se da a partir de la utilización de bienes baratos, los cuales generan una acumulación de capital y por ende fomentan la degradación ambiental. En otras palabras, se puede decir que la máxima apropiación representa la máxima reducción en la composición en valor de la producción de bienes en conjunto en un período dado. Esto se realiza mediante movimientos de frontera que se apropian de los «Cuatro Grandes» productos: trabajo, alimento, energía y materias primas [@Moore2013a].

Es a lo que Moore denomina los cuatro grandes baratos [@Moore2010]. En el ámbito alimentario la comida barata podría fomentar este proceso de degradación ambiental. Si bien la barbacoa es considerada dentro de la comida rápida esta no es considerada barata respecto a los otros tipos de tacos que se pueden adquirir en la gastronomía mexicana. Sin embargo, este precio se puede mantener gracias al aumento de la venta del producto, la sustitución de otros productos más baratos y que no contemplan el impacto ambiental.

Otro de los aspectos que fomentan la degradación ambiental, es la tendencia a la concentración productiva de este platillo, pues más población se ha incorporado en esta actividad debido a que es una actividad con tradición histórica y familiar.

La capacidad de compra de los insumos por la población que se dedica a la venta de barbacoa (ovinos, materias primas, insumos vegetales) ha generado la atracción de vendedores que recorren diversas distancias para ofrecer sus productos; esto genera una huella ecológica al no contar con un circuito corto de comercialización que promueva una economía más sustentable.

Este análisis develó una serie de problemáticas relacionadas con la producción de barbacoa que han originado un proceso de degradación ambiental asociado con la noción de capitaloceno. En este sentido, se han reconocido un conjunto de líneas de acción y de investigación que deben considerarse para profundizar en el estudio de esta región.

Una línea deberá enfocarse en la economía circular, la cual tendrá que reconocer las formas de aprovechamiento de los recursos para evitar impactos ambientales y mejorar las condiciones de vida de la población de Capulhuac. En este sentido, la aplicación de un modelo de economía circular en la cadena de suministros alimentaria, mejorará las condiciones ambientales al reducir los residuos generados por la elaboración de barbacoa. Además de que permitirá generar una diversificación de las actividades económicas en la región.

La economía circular ofrece una vía para replantear estas dinámicas, promoviendo prácticas como el uso eficiente de recursos, la valorización de residuos orgánicos y la generación de cadenas de valor más sostenibles. Sin embargo, la implementación de estos modelos requiere superar barreras tecnológicas, culturales y normativas que limitan su adopción a escala local y nacional.

Otra línea de investigación, deberá abordar la importancia del consumo responsable por parte de los compradores de barbacoa, lo que ayudaría a mitigar el impacto ambiental de este producto. En este sentido, el fomento de estrategias de consumo responsable por parte de los compradores de barbacoa, reduciría el desperdicio de alimentos, así como el uso de materiales no perecederos como los desechables.

## Consideraciones finales {.unlisted .unnumbered}

Nuestro ensayo buscó acercar un caso paradigmático de industrialización de la gastronomía tradicional como parte del fenómeno del capitaloceno. La barbacoa, en un proceso de transición, marcado por los cambios en su contexto y los saberes de las familias de Capulhuac, se convirtió en un fenómeno estructurador de la vida cotidiana de miles de personas. Las prácticas, lógicas y escalas de este sistema producto tienen un impacto directo sobre el municipio de Capulhuac y los espacios con los que se articula. El uso de los mercados y las energías fósiles permitió aumentar la escala productiva a un nivel insostenible. El sistema producto barbacoa de Capulhuac necesita repensarse y reorientarse hacia formas económicas más sustentables de manera progresiva para poder continuar existiendo. Existen múltiples limitaciones y dificultades para una transición hacia la sustentabilidad, pero desde la academia podemos compartir nuestros conocimientos e incidir en las familias para la búsqueda de alternativas graduales que generen nuevas lógicas de interacción alternativas al capitalismo.

El trabajo plasma la importancia de abordar las interacciones entre el capitalismo y la crisis climática desde una perspectiva crítica, reconociendo las limitaciones y oportunidades de la economía circular como un modelo alternativo. En el caso de México, este enfoque no solo responde a los desafíos planteados por el capitaloceno, sino que también ofrece herramientas para atender los problemas nacionales prioritarios mediante estrategias inclusivas y sostenibles que fortalezcan el tejido social y protejan el medio ambiente. Al proponer alternativas basadas en la economía circular, se busca contribuir al diseño de políticas públicas más eficaces y alineadas con los Objetivos de Desarrollo Sostenible (ODS), en particular aquellos relacionados con la acción por el clima, el consumo y la producción responsables, y la reducción de desigualdades.

Como resultado de la dinámica que presenta este contexto territorial, se aprecia un impacto en la economía local como parte del capitaloceno, pues este proceso ha dado lugar a cambios significativos en las economías locales y las estructuras sociales, a menudo priorizando el beneficio sobre la sustentabilidad.

Se hace patente la necesidad de implementar estrategias más sustentables en cuanto la producción de barbacoa, pues el modelo actual es insostenible y perjudicial con el medio ambiente. En este sentido, se reconocen algunas limitaciones y desafíos que enfrenta la transición hacia la sostenibilidad. Entre las limitaciones podemos mencionar una falta del conocimiento de los impactos por parte de las personas qué producen este alimento.

Entre los desafíos se encuentra la adopción de prácticas amigables con el medio ambiente, como los modelos de economía circular; sin embargo, hay quienes critican los modelos de economía circular porque la consideran como una alternativa que potencia el modelo capitalista imperante. Reconocen tanto las limitaciones como las oportunidades que presenta este modelo para abordar la crisis climática y promover prácticas sustentables.

\printbibliography[heading=subbibliography, title={Trabajos Citados}]