---
title: "La vida y los saberes situados en el centro de las tecnologías críticas"
author:
  - name: "Sofía Sienra"
    affiliation: "Universidad Autónoma Metropolitana, unidad Lerma"
    orcid: "0000-0002-6811-7083
"
    email: "sofisienra@gmail.com"
chapter-number: 9
page-range: ""
doi: ""
resumen: |
  En esta entrevista con Eugenio Tisselli se despliega un enfoque crítico de la tecnología que, lejos de asumir la neutralidad despolitizada de la misma, se comprende como una materialización ideológica y, por tanto, como una construcción cultural abierta. La categoría de *reescritura tecnológica* es precisamente una de las aportaciones que el autor ha desarrollado en colectivo para reivindicar la capacidad de agenciamiento frente a técnicas, objetos y procesos que se nos presentan como independientes de los contextos sociales en los que surgen y se propagan. Además de abordar su trayectoria, la conversación indaga sobre las "tecnologías de la vida" del Sur global y el desmarque frente a los discursos dominantes.
  
keywords:
  - "reescritura tecnológica; arte participativo; Sur global"
type: entrevista
---

\addtocontents{toc}{\protect\hspace{1.5em}Sofía Sienra\par}
\markboth{La vida y los saberes situados en el centro de las tecnologías críticas}{}

\begin{flushright}
\Large Sofía Sienra \footnote{Becaria Secihti (Secretaría de Ciencia, Humanidades, Tecnología e Innovación de México, antes Conahcyt) para la realización de una estancia posdoctoral académica en el Departamento de Artes y Humanidades de la Universidad Autónoma Metropolitana Unidad Lerma, con la asesoría de la Dra. Claudia Mosqueda. Profesora a nivel licenciatura y maestría en la UAEMEX. Miembro de las Redes OIADE y Abya Yala. Interesada en el cruce entre estética-política y tecnología desde A. Latina. Contacto: \href{mailto:sofisienra@gmail.com}{sofisienra@gmail.com}}
\end{flushright}

---

\begingroup
\footnotesize

\noindent
Eugenio Tisselli (México, 1972) Es programador, artista, escritor e investigador. Ha desarrollado plataformas de software y metodologías sociotécnicas para la investigación participativa y la escritura colaborativa en contextos urbanos y rurales. Su trabajo ha sido incluido en acervos de arte digital como la Antología de Literatura Electrónica Latinoamericana y Caribeña [[https://antologia.litelat.net/autor-Eugenio_Tisselli]{.underline}](https://antologia.litelat.net/autor-Eugenio_Tisselli) y el Colectivo Ludion [[https://ludion.org/radar.php?artista_id=]{.underline}55](https://ludion.org/radar.php?artista_id=55), entre otros. Sitio web: [[https://www.motorhueso.net/]{.underline}](https://www.motorhueso.net/)

\endgroup

---

\item \personaje\{Sofía Sienra Chaves} Me gustaría comenzar preguntando acerca de tus inicios ¿cómo nace el interés por la programación y el arte digital?

\item \personaje\{Eugenio Tisselli} Podría decir que yo a todo he ido llegando un poco por accidente. Desde que era muy chico, desde lo ocho años concretamente, aprendí a programar. Fui a un curso que hacen para niños, cosa rara acá en México. Les insistí mucho a mis padres que me llevaran y me llevaron. A los ocho años descubrí la programación y quedé fascinado. Obviamente en ese momento no tenía yo donde practicarlo porque en casa no había ordenador, así que pillaba unos cuadernos y me ponía a escribir los programas, así con la pluma, y diseñaba juegos, básicamente. Los imaginaba, los escribía y algunos años después, cuando llegó una Commodore 64 a la casa, ahí los copiaba del cuaderno a la computadora y evidentemente todo fallaba. Pero bueno, empezó así, haciendo juegos, y haciéndolo de una forma muy espontánea, muy natural, como lo hace un niño, sin demasiada premeditación. Entonces la programación ya estaba ahí.

A la poesía fui llegando un poco más tarde, por el típico grupo de amigos, adolescentes que se juntan a leer poesía. Y en ese momento no se me ocurría poner las dos cosas en un mismo espacio —poesía y programación— aunque estaban ahí.

A finales de los noventa me fui a Barcelona, justo a estudiar una maestría en artes digitales, que fue una maestría importante en su momento, porque creo que en todo el mundo de habla hispana era la única dedicada a las artes digitales. Y llegué pensando en música —que también me interesaba— pensando en escritura, pensando obviamente en programación, y no mucho en las artes. Llegué a esa etiqueta de "artes" también por accidente. Pero todo se fue juntando de una manera orgánica y empecé a hacer artefactos digitales que tenían programación, que tenían poesía y alguna intención estética.

\item \personaje\{Sofía} Recientemente ¿a qué te has dedicado?

\item \personaje\{Eugenio} Ahora estoy en básicamente dos cosas, que quizás pareciera que tiene mucha distancia con lo que acabo de contar, pero intento darle una coherencia. Por una parte, estoy cerrando un proyecto muy largo de trabajo con comunidades —específicamente con campesinos en Tanzania— y tiene que ver no solamente con agricultura y sino también con el uso de herramientas digitales, para hacer muchas cosas distintas.[^entrevista_3] Por ejemplo, para el intercambio de conocimientos entre campesinas y campesinos, a través de la creación de entornos donde pueden compartir conocimientos. Una de las partes interesantes, es que junto con Angelika Hilbeck, estamos intentando delinear un marco ético para la aplicación de tecnologías digitales en la agricultura. Me dediqué en los últimos diez años, y al trabajo con comunidades y tecnología en los últimos 17 años.

Por otra parte, estoy totalmente dedicado al Programa de "Arte, Ciencia y Tecnología" de la UNAM. Empecé a trabajar allí en la pandemia y me ha tiene todo el día sentado frente a la pantalla. Es algo que disfruto mucho, porque desde ahí pudimos organizar el seminario de *Reescrituras tecnológicas en México*[^entrevista_4].

\item \personaje\{Sofía} Has mencionado el interés hacia lo comunitario y lo participativo, me gustaría saber ¿Cómo entiendes la tensión* *entre arte y activismo, sus potencialidades y discrepancias?

\item \personaje\{Eugenio} Te diría que en mi cabeza no distingo entre lo que es y lo que no es. Y no por un esfuerzo super-informado posmoderno, sino porque siempre he pensado de esa manera. No estoy creando divisiones tajantes en mi cabeza, y tampoco soy un académico. Sé que se ha debatido mucho sobre arte y activismo, y los encuentros y desencuentros entre esos dos flujos, por llamarlos de alguna manera. En mi vida se juntan de una manera muy natural.

Yo no me considero activista. Soy una persona bastante privilegiada que le gusta la comodidad, pero a veces uno se encuentra en medio de situaciones que te obligan a actuar. Pero no me veo como activista, con esta carga heroica que tienen los activistas, sino simplemente como alguien que si puede hacer algo lo hace y si no puede no lo hace. Y ese "hacer algo" para mí siempre ha implicado la pregunta de: "¿Qué puedo hacer yo?" Si quiero apoyar una causa, qué es lo que yo puedo hacer, qué puedo aportar. Siento que mi actuar ha sido desde lo único que se hacer bien, que es programar. Y un poco el arte es una salida que también permite acompañar al activismo.

Siento que al activismo duro le da igual el arte o no. O sea, la gente que está allá afuera poniendo el cuerpo, si es arte si no es arte le da bastante igual, y siento por otro lado, que hay muchísimo arte que se entreteje con el activismo pero de una manera muy conveniente, por llamarlo así. No estoy criticando nada, simplemente estoy observando ciertas tendencias, que de pronto hay como un *boom* del activismo, por eso me interesa desmarcarme. Porque no me interesa si soy activista, me interesa decir: "Sí, cuando encuentro una causa que me atraviesa la acompaño y cuando no, pues no".

Pienso que ha habido experimentos super interesantes. Hay una corriente crítica del arte electrónico que señala políticas como el capitalismo de vigilancia, el secuestro de datos, la manipulación a través de la inteligencia artificial, los efectos ambientales de las tecnologías digitales. Hay una serie de artistas que desde el ámbito del arte digital se han dirigido a esos temas y eso me parece interesante porque lo siento muy honesto. Como desde el propio ámbito criticar algo del entorno mismo.

La cuestión en la que yo he trabajado es del arte más participativo —si le queremos poner una etiqueta, creo que es la mejor funciona— y también fue por accidente. No es que yo haya dicho: "las tecnologías van a lograr que las comunidades mapeen sus problemas y se comuniquen mejor". No, simplemente fue a través de diferentes encuentros de posibilidades que fueron surgiendo experimentos. En concreto, un proyecto largo en el cual estuve colaborando con el artista Antoni Abad desde 2003, *Megafone*,[^entrevista_5] en el que trabajamos en diferentes países, con diferentes comunidades, muy distintas entre sí, y a partir de ahí fui entendiendo lo que pueden y lo que no pueden hacer las herramientas digitales en una comunidad.

Entonces, si al final es arte, si al final no es arte siento que es un debate interesante que en el fondo a mí no me pesa. Pero sí hay antecedentes artísticos, una intencionalidad artística, un proceso de investigación que puede ser también artístico, hay un objeto estético. Pero después estas cosas derivan por otras vías que se escapan totalmente del arte. A mí me gusta eso, el proyecto en Tanzania empezó como una estrategia artística y en este momento no tiene absolutamente nada que ver con arte. Son derivaciones.

\item \personaje\{Sofía} Volviendo al seminario de Reescrituras tecnológicas que coordinaste, allí se problematizó la asociación de la tecnología como sinónimo de lo digital o de las "nuevas tecnologías", para entender lo tecnológico como un ámbito de lo humano, mucho más abarcativo. En particular me interesa saber ¿Cómo llegaron al concepto de* reescritura tecnológica?

\item \personaje\{Eugenio} Esta es una conversación que hemos tenido a lo largo de años con Nadia Cortés de quien he aprendido muchísimo. Pero justo cuando nos encontramos, hace como seis años, yo estaba ya terminando mi tesis de doctorado. En la tesis había una presencia muy importante de la pregunta por la tecnología. Justamente estaba trabajando en estos proyectos de tecnologías en comunidades, entonces me metí en un campo que yo no conocía —la filosofía de la tecnología— y del cual Nadia ya en ese momento era una especialista. Entonces lo que conversábamos y lo que hemos seguido conversando —porque es una idea que se sigue desarrollando— es cómo cualquier artefacto tecnológico es una materialización de una idea. De una idea de nuestra relación con el mundo.

Cuando pensamos en tecnologías ancestrales, son claramente tecnologías que están dirigidas a cubrir diferentes aspectos de nuestra relación con el mundo donde el cuerpo no alcanza. Esto yéndonos muy atrás, evidentemente. Ahora la tecnología es otra cosa: no es que esté cubriendo necesariamente una carencia en nuestra forma de relacionarnos con el mundo. Si bien no me gusta Disney tengo esta imagen de la película *Fantasía* (1940) donde está el ratón con una escoba mágica que empieza a barrer por sí sola, pero se empieza a multiplicar y pierde el control, y de pronto ya es como una rebelión de las escobas. Siento que nos está pasando lo mismo. En un principio quizá la escoba le ayudaba a limpiar la casa y ahora estamos tan inmersos en un mundo hipertecnologizado, que nos ha llevado a pensar que nuestra única manera de resolver los problemas que ha creado la tecnología es con más tecnología. Estamos como en esta maldición de la tecnología.

Pero cada nueva tecnología que se va creando no deja de ser la materialización —incluso cuando pienso en lo digital pienso en algo material— de una idea sobre el mundo, de toda una ideología. O sea, el solo hecho de que podamos numerizar el mundo ya nos lleva a crear algoritmos que modelan el clima, que modelan las dinámicas sociales, etcétera. Así, emerge la premisa de que todo artefacto tecnológico tiene una ideología y una serie de valores inscritos. Y la *reescritura* de esos valores e ideologías es justamente la que nos interesa abordar. Porque nos llegan tecnologías ya con ciertos valores inscritos, donde ni siquiera nos es dada la posibilidad de reescibirlas para que se dirijan hacia otro lado.

Y entonces surge la pregunta ¿Podemos reescribir las tecnologías? ¿Hasta qué punto las podemos reescribir? Y específicamente en las tecnologías digitales se abre una grieta que nos permite reescribir las tecnologías hasta cierto punto. Casos concretos: el software libre o la utilización de tecnologías en el ámbito del activismo —particularmente tecnologías de control, de productividad, etcétera— para redirigirlas hacia cierto activismo, es una manera, quizá, de reescribirlas.

Las conversaciones más recientes que he tenido con Nadia, han estado encaminadas a preguntarnos por los límites de la reescritura ¿Hasta dónde realmente podemos reescribir? Y llegamos al punto donde decimos: "Vale sí, usar software libre, fantástico". Pero la computadora le pertenece a una mega compañía que extrae los minerales del Congo, se fabrican los componentes electrónicos en condiciones de semi-esclavitud en el sudeste asiático, el internet, son cables submarinos que son propiedad de *Google*, propiedad de *Facebook*, etcétera. Entonces estamos muy felices con *Linux* y todo esto, pero al mismo tiempo estamos siendo partícipes de esta mega-máquina. En definitiva ¿Hasta qué punto estamos atrapados? ¿Qué grados de libertad tenemos dentro de esa reescritura? Y es una pregunta abierta. Tampoco quiero ser totalmente derrotista y decir: "No, la tenemos perdida, y se acabó, chau, vámonos a las cavernas". Pero es una batalla que se libra en el núcleo de la tecnología.

\item \personaje\{Sofía} Me gustaría detenerme en esta idea de los discursos o metáforas dominantes respecto a lo tecnológico. ¿Podrías nombrar uno que te resulte relevante en la época actual, y comentes en qué consiste, de dónde viene y cómo nos afecta?

\item \personaje\{Eugenio} Pienso en la ciencia. Pienso en la ciencia y es un debate muy encendido. Considero que también es muy delicado entrar ahí, pero yo intento atreverme con toda la humildad. No pretendo desmontar la ciencia ni criticarla, pero siento que la ciencia es el típico ejemplo del discurso que nos piensa. Y es el discurso hegemónico por excelencia, creo yo, porque fuera del hacer y del pensar científico todo es superstición, todo es falsedad, todo es un invento, todo es un engaño.

A mí me parece tremendo esto porque la ciencia también está basada en una visión de mundo muy específica, que es una visión occidental, que se puede trazar históricamente. Tiene unos orígenes que empezaron a ramificarse de otras formas de conocimiento, pero que se fueron solidificando en el método científico, en la forma de investigar, etcétera, y que ahora es muy cuestionable. Donde realmente el cuestionamiento debería ser el núcleo de la ciencia. Y de hecho, para la ciencia honesta lo es: un científico o científica honesta siempre está dudando de todo.

Con la pandemia se repetía: "Hay que hacerle caso a la ciencia". Pues sí y no. Porque la ciencia se está cuestionando a sí misma y lo que te dice hoy mañana probablemente va a encontrar que no era así. Pero lo que nos hacen pasar como ciencia es lo incuestionable. Entonces siento que es un peligro porque eso desplaza saberes situados. Desplaza saberes que son vitales, que son funcionales para comunidades que los han mantenido durante milenios, y que de un día para otro están borrados de un plumazo, como si se asumiera: "esto es superstición, esto no sirve", etcétera.

La propia vacuna es una especie de materialización de la ciencia. En este momento quienes la cuestionan son vistos como unos payasos, unos fanáticos. Y sin caer en el cuestionamiento de la vacuna —creo que la ciencia también tiene eso que aportar, tiene sus avances, tiene ese desarrollo— pero, hay que señalar, esta especie de "Deus ex machina" en el que se ha convertido la tecnología. Estamos en peligro, estamos a punto de caer por un barranco, por un abismo como humanidad y de repente llega la vacuna a salvarnos. Cuando en realidad no sabemos nada de la vacuna, no sabemos los efectos a largo plazo, no sabemos si nos va a hacer estériles, si nos va a dañar de alguna manera. No lo sabemos, nadie lo sabe. Pero cualquier artefacto tecnológico que está justificado por una investigación científica ya se vuelve incuestionable.

\item \personaje\{Sofía} Entiendo que ante estos discursos hegemónicos es importante que existan otras perspectivas, por eso me gustaría preguntarte: ¿Qué iniciativas o proyectos recientes consideras que están abriendo el diálogo o que están trabajando a partir de otras perspectivas frente a lo tecnológico?

\item \personaje\{Eugenio} En la agricultura se ve claro en estos momentos, como a partir de la segunda mitad del siglo pasado ha habido una serie de recetas avalada por la ciencia con desarrollos tecnológicos muy claros y efectivos en un primer momento. Se han aplicado literalmente recetas en todo el mundo que han sido, a partir de la Segunda Guerra Mundial, los fertilizantes químicos, los pesticidas químicos, y más recientemente las semillas híbridas, las semillas transgénicas. Digo que se aplican como "recetas" porque se desarrollan evidentemente en los laboratorios muy específicos, dan resultados a corto plazo. Hay también esta pérdida de una visión a largo plazo, de una visión sistémica más holística. Y claro, un fertilizante químico a corto plazo y en un lugar muy controlado como lo es un laboratorio te da resultados impresionantes: las plantas crecen al triple de altura, los frutos son mucho más abundantes.

Ha habido esta idea descontextualizada de la tecnología que lleva a decir: "esto va a salvar al mundo", y ojo que ahí hay buenas intenciones, las cuales quizás están bastante teñidas por esta idea prometeica de traer la tecnología, de traer el fuego, para iluminar a la humanidad. Cuando se aplicaron estos diseños de laboratorio en las famosas "revoluciones verdes" alrededor de diferentes puntos del mundo, y en México, el resultado fue un desastre, porque al acostumbrar a la tierra a los fertilizantes, a largo plazo la tierra ya no se regenera, se la estresa demasiado, y no se regenera de forma natural, y en el curso de tres cosechas la tierra ya es estéril. Entonces se desertificó una gran cantidad de tierra.

Con los pesticidas químicos es lo mismo. Tú tienes una plaga, aplicas el pesticida y claro, la plaga se va, pero también los polinizadores, y muchos otros insectos. En la agricultura se vuelve evidente cómo la aplicación de tecnologías, descontextualizada, sin visión a largo plazo, sin una visión sistémica, ha desembocado en un desastre absoluto, que es en el que estamos ahora.

Las semillas transgénicas, lo mismo. Esta visión de pensar en la vida como una computadora y el DNA como el código, resulta en la idea de: "vamos a hackear el DNA, vamos a cambiar el código y vamos a hacer que la semilla sea resistente a ciertas plagas, sea resistente a los herbicidas, produzca más, necesite menos agua", cuando en realidad la metáfora del DNA como código es totalmente errónea. Son simplemente disparadores que se manifiestan según otros factores externos. Hay mucha manipulación, yo diría manipulación económica, de *marketing* sobre la magia de la manipulación genética, pero en realidad no se entiende lo que se está haciendo. Hay muchos efectos no deseados, no esperados en los experimentos más avanzados con genética. Entonces estamos en pañales, pero se nos vende como si fuese ya una solución probada.

Ante todo esto que te cuento, la iniciativa que a mí siempre me gusta subrayar es la agroecología, que justamente no se trata de negar la tecnología —o sea hay un componente muy fuerte de tecnología en la agroecología— pero es una vuelta a la observación, a la consciencia sistémica, al pensamiento a largo plazo, a la valoración de los saberes situados, a otro tipo de prácticas respetuosas. A repensar la función del parásito, desde la noción de Michel Serres, quien dice que estamos todo el tiempo intentando eliminar al parásito, pero no sabemos si el sistema funciona justamente porque el parásito está allí.

Esa es la mentalidad con la que se trata a los insectos dañinos en la agroecología; no borrarlos, no matarlos, sino hacer de tal manera que su daño se disminuya. Porque incluso el parásito juega una función importante en el ecosistema. Entonces, es toda otra forma de pensarlo, y claro, más allá de ser algo abstracto —los movimientos de agroecología están reflejados en movimientos campesinos, como *Vía Campesina*[^entrevista_6] y muchos otros movimientos— que incluso si ellos mismos no se nombran como "agroecológicos" tienen esos valores de no verse como en contra de la tierra, en contra de la vida, sino *con* la vida.

La verdad es que en el mundo digital me cuesta mucho más ser optimista en este momento en cuanto a iniciativas, por lo que te decía hace rato: está el movimiento software libre que me parece muy bien. Yo también he intentado que todo el software que hago sea libre, abierto, publicado, cualquier persona lo pueda modificar, apropiar, etcétera. Pero al final estamos en máquinas que vienen de no sé dónde y que van a no sé dónde, utilizando redes que son de todo menos nuestras. Y sí, en el seminario de Reescrituras tecnológicas hemos visto iniciativas increíbles como *Telecomunicaciones Indígenas*,[^entrevista_7] *Rhizomatica*[^entrevista_8] (que no estuvo en el seminario), y es una lucha que, siendo honesto, yo creo que es una lucha perdida. A menos que repensemos totalmente lo que significa comunicarnos, lo que significa utilizar tecnologías computacionales, y que lo hagamos en una escala totalmente distinta a lo que lo hacemos hoy: ya no planetaria sino más local. Ahí sí que puede haber esperanzas en ese sentido.

\item \personaje\{Sofía} Ahora bien, me gustaría hablar del contexto latinoamericano y las aportaciones tecnológicas que se pueden generar desde el Sur global. Pensando también en que existe la idea tendenciosa del "rezago tecnológico" de los países "subdesarrollados", y que por tanto habría sectores de la población menos habilitados o legitimados para participar del debate tecnológico. ¿Cómo percibes que se están dando (o no) estas discusiones desde el contexto latinoamericano? Y ¿Existen elementos distintivos en comparación con el Norte global?

\item \personaje\{Eugenio} Pienso que este estereotipo que el Sur global está rezagado tecnológicamente nos hecho muchísimo daño y además es absolutamente falso, desde mi punto de vista. Lo que pasa —pensándolo de una manera muy cruda, pensándonos como animales, en el sentido de que estamos situados en un espacio, vivimos en un entorno específico, y ese entorno tiene un clima y unas condiciones— digamos que los avances tecnológicos que ha aportado el Sur global a la humanidad, han estado totalmente ligados al contexto en el cual se realizaron. Estoy pensando en el maíz y en la milpa.

Otra vez regresando a la agricultura. El maíz es una tecnología en el sentido de que no es una planta que existía como tal en la naturaleza, sino que se fue hibridando a través de generaciones y generaciones, a partir del Teocintle, que si ves esa planta originaria es una espiga pequeñita, que tiene unos granos bastante anodinos. De pronto se va hibridando y llega a ser la planta del maíz que es una maravilla. O sea, la planta del maíz es una creación humana. Y es una creación humana que está en todo el planeta. Yo he trabajado en África, y en muchos países de África el maíz es el cultivo más importante. Claro, lo llevaron los colonizadores, y ahí hay toda una historia bastante sangrienta, bastante tremenda. Pero hoy en día el maíz es importantísimo en Tanzania y Kenia, en países donde he podido estar. El maíz es esta tecnología viva, que se ha adoptado, que se ha cultivado en otros países y que ha alimentado al planeta, de alguna forma. Entonces ya desde ahí se desmiente este mito de que el Sur global no ha aportado tecnología.

La propia milpa también es una conjunción que viene de la observación de cómo las plantas interactúan: maíz, frijol, calabaza, juntos crean un conjunto sinergético que hace que se refuercen todas estas plantas. ¿Por qué estoy hablando de esto? Porque son tecnologías que están ligadas a un contexto en el cual, estamos en un trópico, las plantas crecen, es un espacio fértil. Y es evidente pensar que quizás la aportación tecnológica que pueda hacer el Sur global tiene más que ver con la tierra, que con lo que puede venir del Norte global que son artefactos. Digo, tú te vas a Inglaterra que está lloviendo todo el día, el clima está terrible, y no te dan ganas ni de asomar la nariz. Me quedo en casa cacharreando con las piedritas y los palitos y me invento una máquina. Por qué, porque la tierra no me da nada.

En definitiva, siento que cada cultura situada ha desarrollado sus propias tecnologías, y lo que pasa es que ha habido una hegemonía occidental, que nos ha hecho pensar que los artefactos --hechos primero con piedras y palos, después con metal, después con mecanismos o con códigos-- son superiores a otros desarrollos. Y eso es algo difícil de deshacer. Tenemos como esta adoración por la máquina.

Por lo cual, todo lo que se refiere a tecnologías de la vida —incluyendo también la herbolaria, las tecnologías psicoactivas, los enteógenos— los llamo tecnologías por su aplicación. Son otro tipo de técnicas, tecnologías, artefactos que son considerados inferiores, entonces quizá el giro ontológico, es como voltear la cabeza justamente hacia otra ontología. Por ahí me gusta ver la *Ontología orientada a objetos*, que intenta aplanar todas las ontologías y decir que hay otras tecnologías. Yuk Hui es alguien que habla de este cosmotecnologismo[^entrevista_9] donde no hay una sola tecnología que debamos seguir sino tecnologías que emergen en diferentes sitios y que tienen sentido, son vitales y son igualmente importantes, contextualmente.

La pregunta típica de los gobiernos latinoamericanos de "cómo vamos a salir del rezago" es una pregunta absurda, porque no estamos en ningún rezago. Claro si nos comparamos con Alemania que hace máquinas fantásticas, sí estamos atrás de eso, pero no estamos atrás de muchas otras cosas. Estamos dando vida: del Sur global brota vida. Y creo que mayor aportación que esa no me puedo imaginar.

\item \personaje{Sofía}¿Cuál es la clave para ti del ejercicio crítico? y ¿En qué consistiría el pensamiento crítico en torno a lo tecnológico?

\item \personaje\{Eugenio} Opino desde mi condición de peatón de la teoría. Para mí la crítica es preguntar por todo. Algo tan sencillo como eso y tan complejo. Porque continuamente nos están vendiendo la idea de que hay cosas que son incuestionables. Incluso los discursos de izquierdas, los discursos que parecen objetivamente buenos y positivos, incluso esos. Una consciencia crítica yo creo que no es un deber —o sea que "debes tener una conciencia crítica"— sino que es algo que se debería cultivar desde que somos muy pequeños. Como decir: "sí la ciencia dice tal cosa, pero ¿tú qué crees?" O "¿qué te parece que la ciencia diga tal cosa?" Y que lo responda el niño y la niña. Cuestionarlo todo. Así de fácil. ¿Por qué? Porque cuestionar es la puerta de entrada al conocer.

Cuando tú preguntas por algo realmente creas como una cercanía y a la vez una lejanía con ese algo. Cercanía porque vas a indagar un poco más. Y lejanía porque haces una pregunta y aparecen dos, y son como los Gremlins, que se van multiplicando. Y pasa eso, que esas preguntas te inundan, mientras más preguntas menos sabes, pero al final hace una forma de conocimiento. Entonces la crítica como forma de indagación como forma de conocimiento me interesa mucho.

Y aplicada a los algoritmos pienso en un profesor que se llama Mark Marino Justo él trabaja en temas de literatura electrónica y sacó un libro que se llama *Critical Code Studies*[^entrevista_10] a partir de una clase que tiene con ese nombre, en la cual toma piezas algorítmicas hechas por artistas, entonces entran al código y lo van desgranando, línea por línea, pensando en cosas como: "¿Qué se está asumiendo aquí?". Los algoritmos también son escrituras que materializan ideas y visiones de mundo.

Una aproximación crítica a los algoritmos es difícil porque la mayor parte de los algoritmos no los podemos ver, no los podemos analizar línea por línea. Pero podemos entender lo que hacen: está el famoso algoritmo de *Spotify* donde pones una canción y entonces el algoritmo de alguna manera la asocia con otras canciones, te empieza a recomendar, y empiezas a entrar en este túnel de recomendaciones y te estás dejando encaminar por *Spotify* totalmente. Ahí está clarísimo lo que está haciendo. No sabemos *cómo* lo hace, pero sabemos *qué* es lo que hace. Y es fácil ser críticos con eso porque podemos decir: "me estás dando cosas que crees que me van a gustar y no me estás permitiendo elegir". En realidad sí te permite, pero hay esta sujeción invisible al algoritmo, en la cual las recomendaciones vienen de un lugar superior, mítico, casi religioso, donde el algoritmo que está recomendando esto es porque tiene razón. En ese contexto la actitud crítica es decir: "me da igual el algoritmo, me voy a explorar, me voy a perder y voy a encontrar otras cosas".

Creo que aproximarse de manera crítica al entorno algorítmico es decirle al algoritmo: "¿Por qué me lo estás recomendando?" Hay detrás del algoritmo —lo podemos intuir— todo un cálculo estadístico, matemático, con una autoridad incuestionable. Pero se trata justamente de cuestionar esa autoridad. "Yo sé que la matemática dice que la canción que me va a gustar es ésta, pero a mí me da igual, yo me quiero perder en un universo de sonido y quiero buscar otras canciones que el algoritmo ni sospecha". Y también habría que sospechar que el algoritmo tiene un truco y que quizás la persona o la empresa que maneja a los artistas pagó cierto dinero para que el algoritmo tienda a recomendar esta canción en lugar de esta otra. Tener una actitud de sospecha es más que fundada, porque sabemos que algoritmos y capital están totalmente entrelazados.

\item \personaje\{Sofía} Finalmente quisiera saber ¿Qué tan necesario es saber programar para generar cuestionamientos o pensamiento crítico en torno a los algoritmos?

\item \personaje\{Eugenio} Yo creo que no es necesario programar, pero sí es necesario saber a grandes rasgos qué es un programa. Que un programa es un conjunto de operaciones, que tienen un cierto tipo de lógica, que estas operaciones operan sobre unos datos. Yo creo que basta saber eso, basta saber que son una secuencia de comandos y rutinas y funcionas, como para darse cuenta de que eso puede ser totalmente arbitrario. Que no es una verdad absoluta. Como se nos suele decir: "En el núcleo del universo, en el núcleo de todo ser, de toda célula hay matemáticas ocultas", eso le da una autoridad brutal a las matemáticas y todo lo que esté tocado por las matemáticas es verdadero.

Pero cuando nos damos cuenta de que el código es una escritura, ahí ya la cosa cambia. Es una escritura matemática, pero es una mezcla entre la escritura y matemática. Desde allí podemos razonar: "la gente que hizo este algoritmo podría haberlo hecho de otra manera". De este modo ya se cuestiona esta verdad absoluta del algoritmo y no necesito saber programar, no necesito saber la lógica booleana, las variables, nada de eso. Simplemente saber esas cosas: que el algoritmo es algo escrito por alguien, con ciertos intereses e intenciones.



[^entrevista_3]: *Sauti ya Wuakulima* (La voz de los granjeros) disponible en: [[https://sautiyawakulima.net/bagamoyo/about.php?l=1]{.underline}](https://sautiyawakulima.net/bagamoyo/about.php?l=1)

[^entrevista_4]: El Seminario se realizó entre marzo de 2020 y septiembre de 2021 con la colaboración de diez actores y colectivos vinculados al desarrollo de tecnologías críticas y situadas. Estas experiencias junto con prácticas de escritura colectiva realizadas por las personas participantes (entre quiénes me incluyo) desembocó en la publicación del libro *Reescrituras tecnológicas: imaginar otros territorios* (2023), disponible en: [[https://casadellago.unam.mx/reescriturastecnologicas/]{.underline}](https://casadellago.unam.mx/reescriturastecnologicas/)

[^entrevista_5]: Sitio web: [[https://megafone.net/site/index]{.underline}](https://megafone.net/site/index)

[^entrevista_6]: Sitio web: [[https://viacampesina.org/es/]{.underline}](https://viacampesina.org/es/)

[^entrevista_7]: Sitio web: [[https://www.tic-ac.org/]{.underline}](https://www.tic-ac.org/)

[^entrevista_8]: Sitio web: [[https://www.rhizomatica.org/]{.underline}](https://www.rhizomatica.org/)

[^entrevista_9]: Hui, Y. (2020) *Fragmentar el futuro. Ensayos sobre tecnodiversidad*. Caja negra.

[^entrevista_10]: Marino, M. (2020) *Critical Code Studies*. MIT Press.

