---
title: "La sociedad del cuidado y políticas de la vida"
author:
  - name: "Blanca Estela Melgarito Rocha"
    affiliation: "Universidad Autónoma Metropolitana, unidad Lerma"
    orcid: ""
    email: "b.melgarito@correo.ler.uam.mx"
chapter-number: 8
page-range: ""
doi: ""
resumen: |
  
keywords:
  - ""
type: chapter
---

\addtocontents{toc}{\protect\hspace{1.5em}Blanca Estela Melgarito Rocha\par}
\markboth{La sociedad del cuidado y políticas de la vida}{}

\begin{flushright}
\Large Blanca Estela Melgarito Rocha \footnote{Estancia COMECYT en Universidad Autónoma Metropolitana unidad Lerma. Contacto: \href{mailto:b.melgarito@correo.ler.uam.mx}{b.melgarito@correo.ler.uam.mx}}
\end{flushright}

> **Reseña de:**  
> Batthyány, Karina, Pineda Duque, J. A., y Perrotta, Valentina (Coords.). (2024). *La sociedad del cuidado y políticas de la vida*. Buenos Aires: CLACSO / INMujeres / UNAM / UNRISD. https://doi.org/...


El libro *La sociedad del cuidado y políticas de la vida* propuesto por la Secretaría Ejecutiva de CLACSO y organizado por el Grupo de Trabajo CLACSO *Cuidados y género,* es el producto del trabajo realizado por investigadoras e investigadores de la región latinoamericana en el marco de la 9ª Conferencia Latinoamericana y Caribeña de Ciencias Sociales de CLACSO en México, cuyo eje de análisis se centró en conocer los desafíos teóricos, metodológicos y prácticos para la construcción de una sociedad que valore la aportación de los cuidados y los coloque en centro de la organización social de forma equitativa en la región[^reseña_1]

El libro se integra por ocho textos escritos por personas especialistas en el tema de la "sociedad del cuidado", el hilo conductor del libro está centrado en los avances y desafíos de nuestra sociedad actual para la consecución de una sociedad centrada en el cuidado, esto es, el cuidado de las otras personas con las que compartimos el mundo por parte de todas las personas que integramos el mundo. En este sentido, los textos comparten un horizonte de posibilidad que se escribe en clave feminista: la construcción de una organización social del cuidado en la que el estado asuma una posición activa en la responsabilidad del cuidado y descargue a las familias de dicha labor —por tanto a las mujeres—, asimismo, que sus cursos de acción tiendan hacia la transformación cultural.

De ahí que una preocupación que acompaña al conjunto de los textos es la necesaria construcción de sistemas *integrales* de cuidados en la región que trascienden a las Políticas Públicas focalizadas y superen la idea de que el mercado puede resolver este problema social, este tema no se limita a la academia sino que actualmente se debate su inclusión en las agendas nacionales.

La introducción está a cargo de Javier A. Pineda Duque y Valentina Perrotta, quienes como parte del Grupo de Trabajo *Cuidados y género*, explican que el motivo de la compilación es aportar a la producción de conocimiento acerca de la centralidad actual de los cuidados en nuestras sociedades, así como cuestionar la desigual organización y provisión de cuidados existente a fin de contribuir, desde la perspectiva feminista, al diseño de Políticas Públicas del cuidado, específicamente, aportar a la construcción del sistemas nacionales de cuidado.

El capítulo *Desafíos y oportunidades de la sociedad del cuidado en América Latina y el Caribe,* de Karina Batthyány es una importante aportación a la comprensión del término "cuidados", explica el surgimiento del término primero como problema social y posteriormente como objeto de estudio, respecto del primer aspecto, subraya los avances normativos que se están dado en la región hacia el reconocimiento del cuidado como un asunto público, en ese proceso la aportación de la academia ha sido crucial, ha permitido demostrar que aquello que se ha considerado como privado y del ámbito doméstico es en realidad un aspecto fundamental para el funcionamiento sistémico; respecto del segundo aspecto, la autora explica que la noción "cuidados" surgió no como concepto sino en el sentido común, sin embargo, el pensamiento feminista lo retoma primero para enunciar al trabajo reproductivo en el marco del sistema económico, posteriormente para hablar de trabajo doméstico, de división sexual del trabajo, desigual distribución de las cargas de cuidado, entre otras. Posteriormente, la autora explica a "los cuidados" como un nudo crítico de la desigualdad en la región, ello tiene como base la tendencia predominante en la región de dejar la carga del cuidado en las familias más que en el Estado, el mercado o la comunidad, esto es, en las mujeres. Termina con un llamado a tomar en cuenta lo anterior para la confirmación de una otra forma de organizar el cuidado en nuestras sociedades a fin de colocar en el centro a los cuidados , ello a través de la construcción de sistemas integrales de cuidados que integren el cuidado como un derecho y trascienden a las formas focalizadas de las Políticas Públicas.

El segundo capítulo *El giro conceptual y la ética del cuidado* de Javier A. Pineda Duque, aporta una importante revisión a la literatura acerca del concepto "cuidados" e integra una propuesta conceptual identificada como "Giro conceptual" el cual describe como la forma en que la noción "cuidados" logró la articulación de escuelas feministas, particularmente en torno a la noción "ética del cuidado", para el autor, es desde esta articulación teórico y política que se hace permisible la crítica a los valores modernos, al androcentrismos, a las dicotomías, para el autor esta convergencia teórica y política explica el vasto aumento de la literatura de cuidados en las últimas décadas. Otra aportación interesante del autor es la explicación sintética acerca de la "ética del cuidado", siguiendo a Tronto (2013), avanza en colocar a dicha ética como la base para la construcción de la democracia, lo que implica una importante crítica a la concepción del mercado como proveedor del cuidado e invita a repensar la vida pública y privada. Finalmente, aporta con un importante esfuerzo de síntesis en el que presenta algunas relevantes aportaciones para la construcción de sociedades del cuidado, entre las aportaciones variadas están las relacionadas con dimensiones éticas, subjetivas,emocionales, interpersonales, económicas, estructurales entre otras

El tercer capítulo *Mirando hacia una sociedad del cuidado, pero viviendo bajo múltiples y desiguales formas de producir cuidados: ¿hay luz al fin de ese túnel?*,de Nadya Araujo Guimarães, es una interesante análisis acerca del significado de *cuidar* en la región latinoamericana.En su primer apartado la autora brinda claves de lectura para la comprensión del concepto de cuidados, posteriormente, la autora avanza en una explicación más complicada de "cuidar", la que le atribuyen las diversas prácticas sociales "del cuidar" relacionadas con "circuitos de cuidado", entre ellas está el cuidar como *obligación*, la cual no se vive de la misma manera para el conjunto social toda vez que es una práctica selectiva que recae sobre el cuerpo de las mujeres de forma desigual, por lo que afecta más a aquellas ubicadas en la escala social más baja, dichas obligaciones implican sanciones sociales y jurídicas; cuidar como *profesión*, al que explica como un circuito en el que las mujeres están sobrerrepresentadas, y que en el Sur global tiene distintas expresiones y uno de sus grandes desafíos es la equidad económica; como *ayuda*, se trata de formas de cuidado con base en la reciprocidad en grupos y comunidades. La autora avanza en la búsqueda de claves de lectura para comprender cómo dichas prácticas mantienen otras formas de significar el cuidado relacionadas con el contexto y las relaciones interpersonales no simétricas. Finalmente, desde un horizonte propositivo, la autora cuestiona la posibilidad de construir una sociedad con equidad en la distribución de los cuidados en el marco de una sociedad tan desigual como la latinoamericana y sus divisiones de clase, raza o género, sin embargo, observa una luz en el túnel en las movilizaciones, en la acción y reflexión en la región en torno de la concepción del cuidado como obligación jurídica.

El capítulo *El trabajo de cuidado comunitario: de la invisibilidad al reclamo de derechos*, de Eleonor Faur, aporta una mirada a la noción de "cuidados" desde los cuidados que se realizan dentro del trabajo comunitario. Siguiendo a Arango (2011), la autora parte de la idea de que "el cuidado" es un concepto en construcción al cual se le construye desde miradas disciplinarias, enfoques y posiciones políticas diversas, y sin embargo, explica la autora, ha logrado cuestionar la mirada androcéntrica de la noción predominante de "trabajo", lo que ha permitido visibilizar el trabajo de las mujeres. Explica la autora que si bien el trabajo de cuidados en el mundo se carga sobre las mujeres, no todas cuidamos en la misma proporción, cuida más quien se encuentra en la escala social más baja, de ahí que el trabajo comunitario que realizan las mujeres en los barrios populares de Argentina sea un trabajo invisible. La primera parte del capítulo se centra en explicar la noción de trabajo de cuidados y su relación con el trabajo comunitario, posteriormente, la autora hace un recuento histórico de la organización social y política del cuidado comunitario, en ella la autora explica la proliferación de los cuidados comunitarios a partir de la década de los ochenta tras la crisis económica en Argentina —aunque no se les identificara con la noción "cuidados"—, con la pandemia provocada por COVID, dichas experiencias permitieron cuidar de las comunidades en el contexto de desempleo y pérdida de ingresos. Finalmente, la autora explica que tras la pandemia, y el contexto de las luchas feministas, se ha potenciado la lucha por los derechos laborales y de seguridad social de las mujeres que trabajan en los cuidados comunitarios sea como cocineras, como educadoras, entre otras formas.

El cuarto artículo *La promoción del cuidado paterno. Un debe en América Latina*, de Valentina Perrotta, aporta una perspectiva importante a tomar en cuenta a la hora de pensar la construcción de sistemas integrales de cuidado en nuestros países latinoamericanos, debido a que existen sesgos de género importantes que requieren ser transformados como son las licencias que promuevan el cuidado de las infancias por los varones. La autora parte de la definición de las licencias parentales e identifica tres modelos: las que impiden la igualdad de género, las que permiten la igualdad y los sistemas que promueven la igualación como aquellos que crean incentivos para que los varones se involucren en actividades de cuidado. En la última parte del capítulo la autora aporta una crítica a las licencias existentes en la región latinoamericana con base en una tipología que permite comprender sus tendencias. Finalmente, explica que no basta con "permitir igualdad", es necesario que en la construcción de los sistemas integrales de cuidado que coloquen el acento en el involucrar en el cuidado a los padres y no solamente se limiten al enfoquen maternalista, ello a fin de transformar la cultura de la región.

El quinto artículo *El curso de la vida con derechos. Autonomía, universalidad e igualdad*, de Laura Pautassi, es una valiosa aportación que permite incluir una cuestión rezagada en la región: el cuidado de las personas mayores. En su primer apartado, la autora explica la aportación del feminismo para la construcción de instrumentos de protección de Derechos Humanos que actualmente sirven de herramienta para la demanda a la construcción de Políticas Públicas que viabilicen los derechos mediante sus cursos de acción. Más adelante, explica que la región atraviesa por una tendencia al envejecimiento, sin embargo, no se cuenta con respuestas gubernamentales viables para enfrentar la situación, mientras que la provisión de cuidado a las personas mayores es desigual debido a que está relacionada con trayectorias laborales, por lo que las personas fuera de este ámbito verán limitadas sus posibilidades de recibir cuidado, y disminuyen todavía más si la persona es mujer o de la diversidad sexual. Posteriormente da cuenta del derecho al cuidado como el derecho cuidar, al ser cuidado y al cuidado que es una aportación teórica de la autora desde 2007, y avanza en la explicación de los instrumentos de protección de las personas mayores en la región, particularmente, los establecidos en la Convención Interamericana del 2015 (Convención Interamericana sobre la Protección de los Derechos Humanos de las Personas Mayores, ratificada por México en 2023), por la que los países firmantes se comprometen a adoptar medidas tendientes a desarrollar un sistema integral de cuidados para las personas mayores.

El sexto artículo, *Trabajo doméstico y de cuidado migrante. Culturas emocionales en tensión,* de Andrea Comelin-Fornés, Sandra Leiva-Gómez y Carolina Garcés-Estrada, más allá de la aportación en términos del análisis interseccional: raza, clase, género, migración, las autoras aportan un análisis importante en una dimensión poco explorada de la cuestión "la culta de las emociones en el trabajo", particularmente en el trabajo hogar, que es, por definición, un trabajo de alta interacción entre patrón y trabajador. Con base en las experiencias de vida y trabajo de mujeres migrantes bolivianas en la región Tarapacá en Chile, las autoras explican que el trabajo de cuidados implica un importante desgaste físico y emocional para las trabajadoras del hogar ya que "deben ajustar la expresión de sus emociones a las reglas emocionales de la cultura que prevalece en dicho espacio" (p.189). Entre las cuestiones reveladoras que aporta el texto están: las dificultades de las mujeres trabajadoras del hogar migrantes para cuidar a sus hijos, lo que incide en sus emociones; las asimetrías de poder que se manifiestan entre las partes en el trato y la determinación de las tareas a realizar, en aquello que puede expresarse por las trabajadoras y en la actitud (emociones) que espera de ellas la parte empleadora como son el servilismo, sumisión y disposición —consideradas como como "deseables"—, ello se posibilita por la fragilidad del marco legal y crea una cultura laboral específica.

El último capítulo, *Cuidados y pandemia. Transformaciones en la vida cotidiana de madres trabajadoras y adultas mayores en Chile,* Catalina Arteaga Aguirre y Paulina Osorio-Parraguez, aportan evidencia del impacto provocado por las medidas de distanciamiento social en el marco de la pandemia por COVID en la vida cotidiana de dos grupos de mujeres cuidadoras en Chile, muestran que en este contexto aumentaron los tiempos de cuidados de las mujeres lo que afectó de forma desigual a hombres y mujeres e impactó en la salud física y mental de forma más drástica a las mujeres, entre las aportaciones más importantes está la mirada al impacto pero también la mirada a la resistencia a través de estrategias de cuidado a través de redes de apoyo, búsqueda de espacio para el autocuidado. La experiencia demostró que el cuidado como derecho sigue siendo un desafío.

El libro *La sociedad del cuidado y políticas de la vida* brinda importantes elementos para la reflexión acerca de los desafíos a tomar en cuenta a la hora de diseñar y evaluar Políticas Públicas en la región latinoamericana, es un insumo valioso para el contexto actual y frente al desafío que implica la construcción de sistemas integrales de cuidado.

Si bien considero que sería importante ampliar la mirada hacia otras formas de entender el cuidado, por ejemplo, las que vienen de lugares de enunciación más *integrales* en el sentido de pensar el cuidado de la vida en su conjunto, es decir, no solamente la vida humana, como son las de los pueblos indígenas, lo que es urgente en el contexto de crisis civilizatoria actual, considero que las miradas que vienen desde enunciaciones como las que se pueden leer en este libro encuentran su valor en la disputa de la humanidad por ampliar derechos de *jure* y de *facto*, lo que es sumamente valioso toda vez que aporta herramientas de lucha para mejorar las condiciones de vida de la población, sobre todo de aquella más relegada de los bienes sociales construidos por todos y todas. Por todo ello, recomiendo ampliamente la lectura de este libro.


[^reseña_1]: El evento se llevó a cabo en junio del 2022 en México y contó con el apoyo de CEPAL, UNRISD, Instituto Nacional de las Mujeres (México), ONU Mujeres, Fundación Friedrich Ebert, FESminismos y OXFAM.

