---
# Metadatos ESENCIALES del capítulo
pdf-engine: xelatex
title: "David Lagunas Arias, antropólogo"
subtitle: ""  # Vacío para entrevistas
author:
  - name: "Ignacio López Moreno"  # Quien realiza la entrevista
    affiliation: "Universidad Autónoma Metropolitana, Unidad Lerma"
    email: " i.lopez@correo.ler.uam.mx."
    correspondence: true

# Metadatos ESPECÍFICOS
chapter-number: "10"
page-range: "179"
doi: "198"

# Contenido del capítulo
resumen: |
  David Lagunas Arias es un antropólogo formado en la Universitat de Barcelona bajo la tutela de académicos como Claudio Esteva Fabregat, María Jesús Buxó e Ignasi Terradas. Su especialización teórica se sitúa en la antropología cognitiva y simbólica, orientada al estudio de los esquemas mentales y los Estudios Romaníes. En el año 2000, se trasladó a México, donde ejerció la investigación y la docencia en la Universidad Autónoma del Estado de Hidalgo y en el posgrado de la Escuela Nacional de Antropología e Historia (ENAH). Posteriormente retornó a España, integrándose a la Universidad de Sevilla, institución en la que se ha desempeñado como Director de Departamento. Su producción académica abarca el desarrollo de etnografías de largo aliento enfocadas en comunidades gitanas y en procesos de migración, caracterizándose por una perspectiva crítica y una articulación entre el trabajo de campo empírico y el análisis de las realidades sociales contemporáneas.

keywords:
  - "Estudios Culturales"
  - "Antropología Cognitiva"
  - "Antropología Crítica"
  - "Subjetividades" 
  - "Esquemas Mentales"

# Tipo de documento
type: entrevista
---

\addtocontents{toc}{\protect\hspace{1.5em} Ignacio López Moreno\par}
\markboth{Entrevista a David Lagunas Arias}{}

\begin{flushright}
\Large Ignacio López Moreno\footnote{Universidad Autónoma Metropolitana, unidad Lerma. Contacto: \href{i.lopez@correo.ler.uam.mx}{i.lopez@correo.ler.uam.mx}}
\end{flushright}

---

\begingroup
\footnotesize

\noindent David Lagunas Arias es un antropólogo formado en la Universitat de Barcelona bajo la tutela de académicos como Claudio Esteva Fabregat, María Jesús Buxó e Ignasi Terradas. Su especialización teórica se sitúa en la antropología cognitiva y simbólica, orientada al estudio de los esquemas mentales y los Estudios Romaníes. En el año 2000, se trasladó a México, donde ejerció la investigación y la docencia en la Universidad Autónoma del Estado de Hidalgo y en el posgrado de la Escuela Nacional de Antropología e Historia (ENAH). Posteriormente retornó a España, integrándose a la Universidad de Sevilla, institución en la que se ha desempeñado como Director de Departamento. Su producción académica abarca el desarrollo de etnografías de largo aliento enfocadas en comunidades gitanas y en procesos de migración, caracterizándose por una perspectiva crítica y una articulación entre el trabajo de campo empírico y el análisis de las realidades sociales contemporáneas.

\endgroup

---

\begin{transcripcion}

\item \personaje{Ignacio López Moreno} Muy bienvenido, David Lagunas. Mi nombre es Ignacio López Moreno. Estamos en un espacio que va a ser utilizado por la división de ciencias sociales de la UAM-Lerma. Vamos a conversar sobre tu persona, tu historia de vida, y tu relación con la disciplina. En cualquier momento, tienes derecho sobre lo que estamos grabando, puedes cancelar tu deseo de que sea publicado, puedes pedir modificaciones y contamos con un equipo que se compromete a respetar el *copyright* que compartimos contigo, que formalmente, no tienes que firmar nada, pero que este contrato audiovisual nos vincula y te da el control total sobre el resultado de esta entrevista. Quisieras decir tu nombre, dónde estás, qué día es, qué hora es y si estás de acuerdo con esta entrevista.

\item \personaje{David Lagunas Arias} Sí, mi nombre es David Lagunas Arias, hoy es 25 de febrero de 2023, hora de aquí de España, 18:30 h de la tarde, en Sevilla.

\item \personaje{Ignacio} Perfecto, pues muchas gracias, David, pues entonces comenzamos un poco y como siempre comenzamos por la infancia, nos has dicho que estás en Sevilla, pero no eres de Sevilla. ¿dónde nace David Lagunas?

\item \personaje{Davíd} Yo nací en Badalona porque en el pueblito donde yo crecí que es Sant Adrià de Besòs, que es un pueblito del área metropolitana de Barcelona, no había hospital para nacer la gente. Yo nací en el hospital más cercano, que era en Badalona. Bueno, pues toda mi vida, mi infancia se desarrolla en Sant Adrià de Besòs.

\item \personaje{Davíd} Vivía a caballo entre Sant Adriâ y Badalona. Mi papá tenía un negocio y tenía un negocio de comidas, justamente en un barrio obrero. Entonces, el trabajo de mi papá era, pues, alimentar a los trabajadores, porque estamos hablando de toda esa esa zona de Badalona que fue poblada por trabajadores, obreros, que luego trabajaban en Barcelona, y donde yo vivía en Sant Adrià de Besòs pues sería el equivalente, pues a esas ciudades dormitorio, donde no había nada, pues el núcleo del pueblo, muy chiquitito con su iglesia, su placita y pues una migración muy fuerte también, pero no había nada, no había lugares para pasear, para tomar algo. Y bueno, pues toda la vida se hacía en Barcelona o en Badalona que era más grandes.

\item \personaje{Ignacio} ¿De qué año nos estás hablando?

\item \personaje{Davíd} Estamos hablando de finales de los años 60, periodo de fuerte migración que ya se inició previamente, sobre todo de los años 50 o 60, con mucha población del sur de España, que migraba, atraída por las posibilidades económicas de las grandes ciudades como Madrid, Barcelona y otras zonas industriales, País Vasco, donde había más oportunidades de mejorar la vida.

\item \personaje{Ignacio} Y entonces ¿tu padre tenía era un sitio de comida corrida o era un restaurante?

\item \personaje{Davíd} De hecho, tenía una carnicería en el barrio de Artigas en Badalona que estaba abierta todos los días de lunes a sábado, pero el sábado y el domingo hacía comidas preparadas. Preparaba asados, pollos, conejos, churrascos. Tenía hornos industriales, entonces era como el sábado y el domingo el momento de descanso para los trabajadores, por lo tanto, tenían, digamos, el privilegio de no cocinar en casa y podían ir a la tienda a buscar esos platos preparados.

\item \personaje{Davíd} Era un negocio de mi abuelo que pagaba un alquiler por el local. Porque mi abuelo tenía una masía con mucho terreno, donde cultivaba verduras y hortalizas, en lo que ahora es el barrio de San Roque. Y todo aquello le fue expropiado por el franquismo tras las inundaciones en Barcelona de 1962. Mi familia también recuerda muy bien, toda esta arbitrariedad, del franquismo con expropiaciones.

\item \personaje{Davíd} Por ejemplo, en el caso de mi abuelo, pues fue "te tienes que largar". Y entonces le dieron a cambio un dinero que fue, pues eso, muy poco dinero y aparte el alquiler de una vivienda donde puso el negocio, pero estos terrenos que tenía mi abuelo, que incluso hay fotos y todo en la historia y del barrio. Esto valdría hoy en día un dineral. Entonces los utilizaron para construir pisos durante el franquismo.

\item \personaje{Ignacio} ¿En el mismo pueblo?

\item \personaje{Davíd} En Badalona, ahí a ladito del barrio este que te comento. Pues sí, sí hay recuerdos de eso.

\item \personaje{Ignacio} ¿Cómo es la infancia de David?

\item \personaje{Davíd} Sí, me acuerdo muy bien, estamos hablando de principios de los 70. Mi infancia fue un periodo muy feliz. Toda la vida en realidad somos niños y la vida en realidad es una reedición de lo que viviste de niño.

\item \personaje{Davíd} Sobre todo lo que recuerdo, algo que hemos perdido en nuestras ciudades es la calle. Nosotros hacíamos vida en la calle, éramos niños de 6, 7 años, tú en casa le decías a tu mamá. "Mamá, que me voy abajo". Entonces irte abajo era, salirte a la calle tu solo, y alejarte, cuatro kilómetros de tu casa. Hoy en día esto es impensable. Hoy los niños son como mascotas: los cargan en coches para llevarlos al centro comercial o a las actividades extraescolares y de regreso a casa.

\item \personaje{Davíd} Y nosotros íbamos a buscar a nuestros amigos. No teníamos demasiada televisión para ver porque solo existía un canal de televisión y otro que casi nunca se veía bien. Y en casa éramos cuatro hermanos en un piso de 55 metros. Para mi madre era un alivio que fuéramos a la calle. Ella cuando se casó dejó su trabajo en la compañía Telefónica para criar a cuatro hijos. Se deslomó para que nosotros tuviéramos la ropa planchada, la comida en la mesa, las camas hechas. Una explotación y era una época donde las cosas se veían de otrav manera, como la madre abnegada y sufridora, esa madre mediterránea que sufre por ella y por sus hijos de la que habla Bourdieu en La dominación masculina.

\item \personaje{Davíd} Entonces en la calle siempre encontrábamos a algún amigo para jugar. Y recuerdo con mucho cariño una cosa en nuestras ciudades que eran los descampados. Ya no hay descampados en nuestras ciudades, por ejemplo, Sevilla o Ciudad de México, plantéate cualquier ciudad de tamaño medio o grande, ya no tienen esos descampados. Esos solares que eran los lugares donde los niños desarrollábamos nuestra creatividad y vivíamos en un régimen de semi-libertad. Hacíamos partidos de fútbol, jugábamos a las escondidillas, teníamos muchos juegos. Y yo extraño los descampados, porque ahora lo que hay es solamente construcciones, edificios, han desaparecido los descampados por la especulación inmobiliaria.

\item \personaje{Davíd} Fue una infancia feliz. Me gustaba mucho estudiar y fui el primero de la clase durante toda la primaria y la secundaria. Tenía una memoría prodigiosa y soñaba con ser médico o cirujano. Y también fue una infancia muy ligada al deporte, yo también jugaba al fútbol en el equipo del colegio Sant Gabriel. Uno de los momentos que me impactó más como niño, fue mi primer viaje al extranjero. Te estoy hablando con 7, 8 años, fuimos a Francia varias veces a jugar los torneos de fútbol a París, a Montpellier, a Avignon. Conocimos varias ciudades de Francia por esos convenios que había entre los clubes deportivos y jugamos torneos internacionales. Y eso lo recuerdo también como un momento clave de abrir los ojos a un mundo más avanzado, con mayor progreso y otro nivel de vida que, además, a mí también siempre me encantaba ir a Francia porque veía muchos avances. Veía casas muy grandes, muy amplias, a diferencia de nuestros barrios, porque España es un país de pisos, es un país de construcciones muy altas, de pisos altos y feos de esa vivienda franquista. En Francia veías esas casas rodeadas de muchos árboles, muchos campos, los campos de fútbol de hierba que no los conocíamos nosotros acostumbrados a jugar en campos de tierra. Teníamos tal vez mucha más libertad y la calle, la calle era nuestra.

\item \personaje{Ignacio} Si esa frase se escucha mucho, es su momento.

\item \personaje{Ignacio} Tú vas creciendo todavía viviendo en el mismo pueblo, ¿cuándo entras en contacto con la antropología?¿Qué es lo que te vas acercando a eso? Porque ya de momento esta idea de ver formas de vida diferente de viajar es algo como muy dentro de este *ethos* antropológico, de las cartas persas, de ir viendo.

\item \personaje{Davíd} Bueno, en realidad yo no, yo no sabía. Yo tenía una relación más natural, por ejemplo, con otro tipo de gentes diferentes a mí, que era, por ejemplo, los gitanos ahí donde te dije que se había expropiado este gran terreno agrícola a mi abuelo. Ahí se construyeron muchos pisos para alojar a muchas familias, entre ellas familias gitanas. Entonces, algunas de esas familias gitanas, venían con frecuencia también al negocio de mi padre a comprar y mi padre tenía muy buenas relaciones con estas familias. De hecho, yo recuerdo de niño que siempre nos sorprendía cuando una persona de etnia gitana venía a comprarnos porque siempre compraban a lo grande, venían y pedían 50 pollos, 100 pollos, eran muy dados a comprar comida para sus celebraciones, sus bodas, bautizos. Y, de hecho, pues a mi padre siempre lo consideraron como el amigo de los gitanos y así le decían, "tú eres el amigo de los gitanos". Entonces, el primer contacto con la con alteridad que luego fue también uno de los temas que también me han interesado mucho, el tema de los gitanos y los romaníes, pues empezó por ahí, de ver a estas gentes que llegaban al negocio de mi padre y que no parecía importarles el dinero que gastaban.

\item \personaje{Davíd} Y te estoy hablando de la adolescencia donde claro, también me integré en las pandillas, tu grupo de amigos del barrio. Y en aquel tiempo en las pandillas había muchas tribus urbanas, heavies, punks, siniestros, modernos, neohippies. Es decir, era también una forma de entender un poco esa alteridad a nivel urbano.

\item \personaje{Davíd} Entonces conocíamos muchas otras pandillas de otros lugares y nos relacionábamos con ellos en los bares, que esto es muy interesante. El tema de que en aquel tiempo no había WhatsApp, entonces, ¿dónde quedabas? Quedábamos en el bar el sábado, por ejemplo, a las 17:00 h de la tarde. Entonces a medida que llegabas iba llegando tus amigos y a partir de ahí pues nos juntábamos. El bar era un elemento de socialización de primer orden.

\item \personaje{Davíd} Es más, la vida de barrio se hacía en los bares. Si habían bares es que había vida, había vida social. Y recuerdo también una cosa que era la importancia que tenían los pequeños comercios, o sea los pequeños locales, como las ferreterías, las peluquerías, la panadería. Hoy en día ya no se come buen pan, por ejemplo, en la panadería. Todo eso hacía el tejido de barrio.

\item \personaje{Davíd} Era un tejido social muy, muy, muy interesante, donde los vecinos nos relacionábamos. Y esto poco a poco ha ido desapareciendo, es cierto, entonces esto forma parte hoy en día ya o debería formar del patrimonio urbano de las ciudades, esos pequeños comercios que son fundamentales y no debería permitirse que fueran desapareciendo en favor de estas cadenas o franquicias que han pues transformado nuestras ciudades.

\item \personaje{Ignacio} Si, la aparición de esos no lugares…

\item \personaje{Davíd} A mí me gustaban mucho los documentales, sobre todo de la cadena de TVE, la 2. Eran muy frecuentes los documentales, entonces me gustaban mucho esos documentales de lugares exóticos, tipo "Otros pueblos" de Luís Pancorbo. Ya tenía interés en conocer y esto en realidad con el tiempo como dice Steve Jobs "vas conectado los puntos". Con esas pandillas con las cuales me movía había mucha influencia del movimiento anarquista. Y entre el anarquismo y el gusto por viajar ya iba configurando mi propósito.

\item \personaje{Davíd} En el fondo pienso que ha sido un poco influencia el anarquismo en mis decisiones que he tomado y en relación con la antropología porque yo también estaba muy insatisfecho con mi sociedad con donde había nacido, donde vivía era mi pequeño mundo, la ciudad dormitorio. Entonces sentía que mis horizontes estaban muy limitados y no estaba conforme con la sociedad.

\item \personaje{Davíd} Tenía una ideología política con tendencias anarquistas y de izquierda. Y tampoco estaba contento conmigo mismo, ya sabes esa etapa de la adolescencia la cual es la más crítica en la vida de un individuo y que es una etapa de cambios y estás madurando. Entonces no estaba contento con la sociedad ni contento conmigo, esto es algo que le doy la razón a José Contreras quien se refiere a lo que en los 70 ya se comentaba: el que no estaba contento consigo mismo estudiaba psicología, el que no estaba contento con su sociedad estudiaba sociología y el que no estaba contento consigo mismo y con su sociedad estudiaba antropología. Mi epifanía fue un hecho anecdótico, un detalle nimio. Antes de estudiar el bachillerato, vi una entrevista en un periódico y era una entrevista a un tipo que se describía como etnólogo y aventurero. No recuerdo su nombre, era francés. Pero el titular de esa entrevista decía "el paraíso está en uno mismo". Entonces, me fascinó esa figura del etnólogo y aventurero, esta idea romántica de viajar. Yo lo que quería era viajar, quería conocer otros mundos, se supone que estudié antropología para viajar y esa entrevista me marcó mucho. Y fue de alguna manera más adelante, ya estaba en el último año de bachillerato y ahí podía decidir qué estudiar y no estudiar, si estudiar antropología o no. Y fue otra epifanía, otro momento de claridad, que vino a definir mi destino.

\item \personaje{Davíd} Andaba por la Rambla de Cataluña de Barcelona paseando y en una papelería vi en el escaparate que tenían, aparte de los bolígrafos, los materiales típicos de oficina, unas muestras de tarjetas de visita. Y en una de estas muestras de tarjetas de visita, me acerqué a la vitrina, decía Claudio Esteva Fabregat, Etnólogo. Y exclamé, "¡Vaya!". Me di cuenta de que la etnología era una profesión tan normal como cualquier otra. Y dije pues esto de viajar, de que yo había visto en los documentales a los antropólogos que iban con las tribus y que se metían en la selva, en el Amazonas, es decir, es una profesión como cualquier otra. Porque ahí está la tarjeta de visita en una papelería de Barcelona. Por lo tanto, empecé a buscar en la Universidad en los planes de estudio y vi que existía la antropología. Y eso fue también la confirmación de que no estaba errado.

\item \personaje{Ignacio} ¿Cómo fue tu Facultad de Antropología?

\item \personaje{Davíd} Yo me integré en el en el plan de estudios de la Facultad de Geografía e Historia de la Universitat de Barcelona, donde existía la especialidad de antropología cultural. Eso significaba que, en los primeros cursos, primero y segundo curso, teníamos que cursar materias de otras disciplinas, de las Ciencias Sociales. Y alguna de antropología.

\item \personaje{Davíd} Y en los dos últimos cursos ya podíamos elegir más asignaturas de antropología y salíamos con la especialidad. El sistema de la Universitat de Barcelona era un sistema muy bueno porque era una especie de menú a la carta. Había algunas asignaturas troncales, pero luego teníamos cierta flexibilidad para pues cursar una asignatura de biología como antropología física o irnos a la Facultad de Bellas Artes y cursar otra asignatura.

\item \personaje{Davíd} Teníamos muchas más posibilidades, de hecho, yo creo que, eso también fue determinante porque yo estudié tal vez en el mejor departamento de antropología del Estado español, que es el departamento fundado por Claudio Esteva Fabregat. El impulso que Claudio le dio a la antropología en la Universidad de Barcelona, pues acabó convirtiéndolo en un referente académico a nivel estatal y europeo, en investigación, en docencia y atrayendo también mucha gente talentosa. Tuve la fortuna también de conocer y acercarme a los primeros representantes de la generación de antropólogos, precisamente. Todos estos discípulos que se habían formado con Claudio Esteva Fabregat, entre ellos, María Jesús Buxó y Ignasi Terradas y otros un poquito más que provenían de otros rumbos como Dolores Juliano, por ejemplo, que me abrió toda la perspectiva americana. Las clases de Dolores Juliano, yo la recuerdo, pues perfectamente porque su etnología de América me pareció fascinante y fue mi primer contacto que tuve con la diversidad americana. Luego Manuel Delgado, tal vez y puedo decir que todos ellos me influyeron mucho. Joan Bestard y la claridad que transmitía. Ignasi Terradas es uno de los que realmente me impactó más. Es el mejor lector que existe en antropología. Es un gran lector. Entonces sus clases eran grandes discusiones acerca de etnografías clásicas. Y esto María Jesús Buxó nos lo había dicho, que la vida y la formación de los antropólogos era hacer etnografías. Eso me lo tomé como mi principal objetivo profesional: hacer buenas etnografías.

\item \personaje{Davíd} Y eso es algo que se me ha quedado muy, muy grabado, a pesar de que tú sabes tanto en México como en España toda esta nueva, digamos política, de equipararnos a las Ciencias Naturales, todo el tema de la burocracia y el asunto del modelo neoliberal y gestión empresarial que se implanta en nuestras instituciones ha hecho que los antropólogos tal vez hayamos sido muy castigados. Sobre todo, en las acreditaciones, en las evaluaciones, porque las etnografías han dejado de contar, ahora cuentan los artículos de alto impacto,

\item \personaje{Ignacio} A parte también porque se nos han controlado los tiempos y la etnografía requiere tiempo.

\item \personaje{Davíd} Claro, lo que nos enseñaba Ignasi Terradas en todo un curso era leer con paciencia una etnografía, desde el principio hasta el final. Y esto es algo que nos inculcó y es algo que tengo que agradecer: la paciencia científica, la investigación larga e incierta. No esta investigación de proyectos por financiación de un magnífico proyecto Europeo o del CONAHCYT que tenemos que cumplir con un periodo con un informe, utilizando un lenguaje que sea atrayente para estos evaluadores. He ido practicando este tipo de investigación larga, toda la vida en ello, realmente en te involucras en cuerpo y alma en resolver esa cuestión que te has planteado y que debes resolver.

\item \personaje{Davíd} También estoy muy agradecido por la oportunidad que tuve de tomar clases en la Facultad de Bellas Artes con Alberto Cardín, uno de los *enfants* terribles de la antropología de España. Recuerdo que el curso que tomé con Alberto Cardín fue magnífico. Alberto no pudo o no quiso incorporarse al departamento de antropología de la Universitat de Barcelona, y estaba allí en la periferia, en la Facultad de Bellas Artes, explicándole a los futuros escultores e historiadores del arte cosas de antropología. Todavía recuerdo aquel curso poco antes de morir que fue realmente también impactante. Esas clases fueron un privilegio que también me ha marcado mucho. Alberto Cardín me marcó mucho y agradezco haberlo conocido.

\item \personaje{Ignacio} Una cosa me llama la atención. Estás hablando de esos tiempos, pero sin embargo eres una persona muy productiva, escribes mucho, muchas cosas que creo que muchas veces la gente no quiere leer porque contienen verdades que pueden ser difíciles de digerir. Ya llegaremos a ese tema. Una de las cosas que me resultó muy curioso, la primera vez que oí hablar de ti, tú hablabas de antropología cognitiva.
\
\item \personaje{Ignacio} ¿Qué es la antropología cognitiva? Porque la gente ha oído hablar de antropología cultural, de antropología social, de antropología crítica, pero poca gente oye hablar de antropología cognitiva. Tienes un libro precisamente de métodos, que lo explicas y que lo pondremos en las referencias para quien quiera consultarlo. Pero ¿por qué te llama la antropología cognitiva y en qué consiste?

\item \personaje{Davíd} Bueno, fue una influencia precisamente de María Jesús Buxó. María Jesús nos brindó magníficos cursos y seminarios de antropología cognitiva en la Universitat de Barcelona. Entonces, nos abrió a algunos de nosotros, muchos de los horizontes intelectuales y una serie de perspectivas que desconocíamos. Entonces ya tenía esa base, gracias a que María Jesús había estado trabajando en las universidades norteamericanas, y había estado en Nuevo México, sobre todo. Y tenía una formación pues magnífica en antropología cognitiva. Uno de los conceptos más útiles en los últimos años ha sido el de esquema mental. Lo ha desarrollado el que fue mi director de tesis doctoral, Leonardo Piasere de la Universidad de Verona. A Piasere lo conocí cuando fui a ver a Ignasi Terradas para que fuera mi director de tesis y me dijo que buscara al mejor especialista en Estudios Romaníes del mundo. Ese era Leonardo Piasere. Cada año hacía dos o tres viajes, agarraba un avión desde Barcelona y me iba a Verona o a Florencia, a trabajar con él en su casa para la tesis. Escribió un libro muy interesante que se llama *El etnógrafo imperfecto*, un libro poco conocido en España y que fue una revelación. De este libro me interesaron varias dimensiones: el concepto de esquema mental y su transformación en un modelo cultural, lo cual explica el racismo de otra manera, no solo desde el simbolismo. En ese libro es donde habla de la teoría de los esquemas mentales que ha sido muy útil para los estudios cognitivos. El concepto de esquema pienso que es un concepto que nos ayuda a entender cosas como el racismo, nos ayuda a entender los prejuicios y los estereotipos, y también todos estos elementos comunes que tenemos como seres humanos que son una serie de procesos mentales que son universales, más allá de las particularidades de cada cultura. Entonces, la idea de los esquemas mentales es algo que me ha influido mucho. Por ejemplo, la cultura es un conjunto de esquemas mentales, es esto que tenemos en la cabeza, pero que nos permite actuar. Por ejemplo, en una acción tan cotidiana como "me lavo los dientes" tú necesitas tener el esquema previo para, digamos, ir al baño, agarrar la pasta de dientes, abres el grifo, mojas la pasta de dientes en el agua del grifo, te cepillas los dientes durante un minuto, te enjuagas la boca, cierras el grifo, limpias\... todo esto que es una operación tan sencilla es un esquema mental. Muy sencillo, de base, pero es un esquema. Podemos hablar de esquemas mucho más generales, más complejos, como el esquema amor o el esquema "romance". ¿Qué es un romance? Todo el mundo tiene una idea: salir a cenar juntos, pero no a un McDonald\'s tal vez a un buen restaurante o un restaurante caro, o significa ir al cine, o hacer cosas locas como subirse juntos a una montaña rusa o hacer un viaje. Creo que también es un avance muy interesante.

Carlos Reynoso, también en solitario, ha desarrollando también en Argentina avances en antropología cognitiva. He hablado varias veces con él en Buenos Aires y en su casa de Tigre comiendo una rica parrilla de carne. A Leonardo Piasere le agradezco su maestría y sus enseñanzas. Cuando iba a verle y tomaba el avión desde Barcelona hasta Verona trabajábamos mi tesis sobre los Gitanos catalanes en la biblioteca de su casa. Recuerdo el primer día de trabajo, a las cinco de la tarde, que me dice: "escríbe y dibuja todos los esquemas de las alianzas matrimoniales de la comunidad de los Gitanos catalanes de Mataró. Vuelvo en un momento". "Guau", pensé. Me quedé dos horas haciendo cartas de parentesco y genealogías. Fue uno de los exámenes más duros de mi vida. Después, como la cosa fue bien fuimos a comer a un restaurante cerca de un río en Verona donde servían la mejor carne de caballo de la región. Conviví con los Gitanos catalanes, varios de ellos parientes de Peret el rey de la rumba, y a través de la observación participante acabé siendo uno más. Esto fue del año 94 al año 98. Y escribí en México cinco años después "Los tres cromosomas", el libro basado en esa tesis doctoral. A los Gitanos catalanes les importaba un bledo si yo estaba escribiendo una tesis para un avance de la ciencia, lo que vieron en mí es que era una persona "buena" y de hecho fui adoptado por una de las familias que me trataban como un hijo más.

\item \personaje{Ignacio} Eso muchas veces al alumnado les parece un mundo, ¿cómo consigues hablar con alguien? ¿cómo entras?

\item \personaje{Davíd} Muy sencillo. Primero de todo, con empatía. Tienes que andar con empatía y con humildad. Entonces ellos me dieron la clave, de hecho, los Gitanos\... yo era el único "payo", el único no gitano que estaba con ellos todos los días, todas las tardes, tomando café, los acompañaba a sus bodas, a sus funerales, a sus juergas.

\item \personaje{Ignacio} Las comidas que de repente te pusiste al lado de ellos.

\item \personaje{Davíd} Sí.

\item \personaje{Davíd} Ellos mismos me dijeron: "mira David. Tú si quieres caer bien, tú vienes aquí, te presentas y dices \'hola, soy antropólogo. Me gusta mucho la historia de las costumbres, de los Gitanos. ¿Te puedo invitar a tomar un café?\'. Parace sencillo y no lo es.

\item \personaje{Davíd} Hay que entender los códigos. Tomarse un café con una persona de etnia gitana es mucho más importante de lo que nos imaginamos. Tomarse un café con alguien ya indica una situación de comensalidad y es una forma de establecer un primer contacto. Y con los Gitanos siempre me ha gustado hacerlo porque forma parte de su regla cultural. No tengo que pensar lo que tengo que decir o hacer, si decir "buenas tardes" o no decir nada. Tengo incorporada la regla. Es un conocimiento incorporado que dice Piasere: si sigues la regla, como dice Wittgenstein, puedes comprender la regla, la cultura. Y ya te desenvuelves de manera natural entre tus interlocutores porque has comprendido la regla. Como invitarles a un café, lo haces automáticamente y sin reflexionar sobre el qué o el cómo. Simplemente lo haces. Porque tienes que hacerlo. Y con ese gesto se inicia una cadena, y sobre todo con esta dosis de humildad.

\item \personaje{Davíd} Ellos, lo que ven es otras cosas en ti, una cierta nobleza de sentimientos. Ellos me dieron la clave… "tienes buen corazón", porque su modelo cognitivo es otro. Nuestro modelo cognitivo como científicos es hacer etnografías, explicar nuestros hallazgos en un texto, en un congreso, en una ponencia, en un aula. Así funciona nuestro oficio, ese es nuestro modelo cognitivo. Pero el modelo cognitivo de otros pueblos es otro. Entonces el de ellos se basa en una idea moral muy simple: "buen corazón". Y es esta una metáfora que utilizan: "tienes buen corazón",

\item \personaje{Davíd} Entonces si tienes buen corazón, esa anomalía que representas al haber llegado sin que te hayan convocado, pues poco a poco se va abriendo un camino en positivo y esa anomalía acaba siendo integrada. Es más, en muchos casos, todos aquellos grupos que han hecho trabajo de campo con comunidades gitanas al final han sido adoptados por familias, a ese nivel de compadrazgo, e incluso alguno de ellos se acabó casando con una Romani como Patrick Williams. Se trata de conocer los códigos, conocer los contextos y no es tan complicado como parece, teniendo en cuenta que el trabajo con los Gitanos es uno de los más difíciles del mundo. Es un grupo que no acepta este tipo de investigaciones, lo han visto tradicionalmente como una intrusión, no se suele incorporar en esas comunidades a un antropólogo. Incluso hay relatos de varios antropólogos que han escrito sobre su fracaso al no poder de incorporarse en las comunidades. Es el relato honesto de un fracaso como el de SusanDiGiacomo de la Rovira y Virgili de Tarragona, el relato de su fracaso con un grupo rom itinerante en España. Maravilloso relato.

\item \personaje{Ignacio} Eso nos lleva a la antropología cognitiva, de que ellos tienen una construcción de la interacción basada en sus propios códigos. Entender eso es en lo que se basa la antropología cognitiva.

\item \personaje{Davíd} La antropología cognitiva busca los procesos de cognición, que son los procesos mentales que nos permiten percibir, resolver problemas, gestionar la información. Son procesos mentales cotidianos. En las clases que doy de antropología simbólica en la Universidad de Sevilla hay un módulo dedicado principalmente a antropología simbólica que plantea una serie de avances interesantísimos: Dan Sperber, Pascal Boyer, Roy d\'Andrade, Maurice Bloch. Hay toda una bibliografía super interesante acerca de nuevas perspectivas que complementan la visión clásica del simbolismo, de la escuela de Clifford Geertz, Víctor Turner.

\item \personaje{Ignacio} Pero entonces hay una pequeña parte de descripción densa de esquemas, o sea, tienes que escribir de manera densa, ¿pero sin interpretación teórica o con interpretación teórica?

\item \personaje{Davíd} Claro, claro, con interpretación teórica, es decir que aquí tenemos buena literatura al respecto. Entonces, claro, yo me di cuenta de la importancia que tiene la antropología simbólica cuando el propio Maurice Bloch dice que ir a comprar a un supermercado exige mucho trabajo mental y es una acción muy compleja cuando tú te metes en el supermercado y tienes que ir por los pasillos caminando para buscar la comida. Eso es algo cotidiano. Es un proceso cognitivo muy complejo, exige mucha coordinación en tu mente y más cuando cambias de supermercado, vas a un supermercado que no conoces fuera de tu supermercado habitual. Porque te puede dar un ataque de ansiedad cuando no encuentras dónde está el pan, dónde está la harina.

\item \personaje{Ignacio} Del mismo supermercado y de repente si la puerta ya no está por la izquierda, sino que está por la derecha y accedes a otro punto del supermercado, te rompieron el esquema.

\item \personaje{Davíd} Claro.

\item \personaje{Ignacio} Si te vas al otro lado, o lo intentas al revés.

\item \personaje{Davíd} Claro, son esquemas que se llaman esquemas de orientación, son esquemas de orientación en los que hay diversos niveles.

\item \personaje{Ignacio} El mercado del tianguis como quintaesencia de espacio de interacción humana. Cuando vienes de fuera resulta super interesante, porque todos tienen sus zonas de comida, tiene la zona en la que están determinados tipos de alimentos, otras zonas. Pero cuando tú te enfrentas a eso te enfrentas a una masa informe que no consigues interpretar. No, no sabes por dónde tienes que ir y pues muchas veces simplemente sigues la corriente, observas que hace la gente y asumes. Y bueno, es muy interesante para quienes no conozcan este tipo de… ¿subdisciplina?, ¿aproximación? Porque yo creo que con ese tipo de categorizaciones me pierdo…

\item \personaje{Davíd} Bueno, en algunos planes de estudios está fusionada con la simbólica, es decir, por ejemplo, creo recordar que en el plan de estudios de la Universidad de Tarragona y la Universitat Oberta de Catalunya hay un grado en cultura y evolución humana, y la asignatura se llama antropología simbólico-cognitiva. Ellos sí se dieron cuenta de que están unidas.

\item \personaje{Davíd} Y es muy interesante el caso de la alimentación. Bueno, tú sabes cómo experto que bueno, cuando tú entras a un restaurante tú tienes que seguir un guion, hay un patrón y todo el mundo tiene el esquema en la cabeza. ¿Cómo te tienes que sentar? ¿Cómo tienes que ordenar al camarero? ¿Cómo darle las gracias? ¿Qué haces con los platos? ¿Los recoges tú como en McDonald\'s? ¿Cómo pagas? ¿Qué significa comer en un McDonald's y qué significa comer en un restaurante 5 estrellas Michelín? ¿Con quién vas a comer al McDonald\'s y con quién vas a comer a un buen restaurante?

\item \personaje{Davíd} Por ejemplo, si estás en un proceso de enamoramiento o de romance, pues ese restaurante es más adecuado, como te decía. Todas las decisiones que tienes que tomar cada día, por ejemplo, a la hora de la comida, qué es lo que tienes que comer en el desayuno, el almuerzo y la cena son decisiones que tienes que tomar diariamente. Pero que obviamente necesitas de una configuración mental, una representación, que de alguna manera siempre remite a la memoria, es decir, en la memoria tienes toda la información almacenada para pensar y actuar de manera correcta en base a la experiencia.

\item \personaje{Ignacio} Porque precisamente está ese esquema de eres joven y no puedes ir a un restaurante porque es muy caro. Aparecen este tipo de espacios y yo recuerdo cuando vine la primera vez a México estuve un tiempo haciendo observación de los McDonald\'s. Me llamó mucho la atención la materialización que tienen aquí es diferente de allá. Veía que era un restaurante más caro, no era popular. Yo me encontré muchas personas que no iban a clase, había muchas chavas y chavos con la maleta de que no habían ido a clase. En el McDonald\'s de San Carlos. Era un refugio juvenil de determinados jóvenes. También de padres divorciados que no saben cocinar y cuando tienen que cenar con los niños los llevaban al McDonald\'s. La verdad que es muy interesante esto de la antropología cognitiva. Y dentro de tu biografía pues destaca que viviste en México bastante tiempo. ¿Cómo se llega de la antropología catalana a cruzar el Atlántico? Porque sabemos que tu viste aquella entrevista a un etnólogo y aventurero y dijiste, "no manches, voy a ser antropólogo y aventurero. El cielo es el límite"

\item \personaje{Davíd} Retrospectivamente, en aquel momento, año 2000, me doctoré. Y estaba saliendo del acto con el tribunal de mi tesis doctoral y uno de los profesores que había estado en el tribunal me dijo que en la secretaría de la universidad había algunas becas y había un programa de movilidad con México. Entonces fue una casualidad y también si en ese momento me hubiera surgido la posibilidad de irme a Australia o Papúa Nueva Guinea, o donde sea me hubiera ido. Yo lo que quería era trabajar de antropólogo. Entonces en la Universitat de Barcelona en aquel tiempo, no veía posibilidades de poder incorporarme. También me parecía detestable la idea de rendirle pleitesía a los catedráticos para conseguir favores o palancas como observaba en otros compañeros de carrera. Entonces tenía que romper con todo y hacer mi bautismo de fuego en otro país. Es como Martin Sheen al inicio de Apocalipsis Now: "Yo quería una misión. Y por mis pecados me dieron una". Y fue México donde hice mi ritual iniciático. México y España tenían un programa de cooperación de incorporación de jóvenes doctores españoles en universidades mexicanas. Claro, no a la inversa, es decir, este programa no servía, recíprocamente, para que jóvenes doctores mexicanos pudieran incorporarse a universidades españolas. Entonces teníamos un privilegio. Es cierto, en aquel tiempo la Agencia Española de Cooperación Internacional desarrolló este programa y tú podías venir a México durante 2 años. Estuvo funcionando durante muchos años, creo que se canceló en el año 2010, me parece. Y yo me fui en el año 2000, es decir, 3 meses después de doctorarme hice la solicitud y me contestaron positivamente. Vendí mi casa, vendí mi coche, regalé a mi perro y m,andé a paseo a mi novia y lo dejé todo. Y me fui con una maleta, ropa y varios libros en un vuelo.

\item \personaje{Davíd} Me incorporé a la Universidad Autónoma del Estado de Hidalgo. Una universidad joven que en aquel momento estaba muy comprometida con cumplir con todos los requerimientos del sistema de educación mexicano de evaluación de las universidades. Esta universidad atraía investigadores extranjeros y de Ciudad de México con el objetivo de crecer, tenían una política muy abierta de contratación de doctores. Estoy hablando de universidades periféricas, tal vez las grandes universidades como la UNAM, la UAM, que ya tenían, digamos a una buena masa crítica no tenían tanto interés en formar parte de este programa de visitantes. Pero claro, en aquel tiempo te estoy hablando del año 2000, México no generaba un número importante de doctores al año y por eso había interés en traer a doctores españoles.

\item \personaje{Davíd} En México se ha desarrollado mucho la antropología, están muriendo de éxito, hay muy pocos antropólogos que ganan mucho dinero y forman la élite y muuchos que no les alacanza o no encuentran trabajo. Pero en aquel tiempo, pues México desarrollada, no sé, 2000 doctores al año, no lo sé cuántos quizá menos, no me acuerdo de las cifras, entonces era un aporte muy interesante. Para mí esta universidad fue mi primer entrenamiento, un trampolín. Era una universidad muy politizada, en manos de un grupo político, pero que me dio muchas posibilidades, muchas facilidades y en esto agradezco enormemente las facilidades que brindó precisamente para muchos de nosotros. En España no teníamos esas posibilidades, doctores en diferentes ciencias, entre ellos, en antropología. Y tuve mucha libertad de desarrollar mis primeras investigaciones. Aquí ya empecé a creerme que no me había equivocado de profesión. México lo vi como un paraíso para los antropólogos. Tal vez esto sea una exageración y una idealización, pero el hecho era que el mercado de trabajo para un antropólogo era estructuralmente mayor en México. Y contaban con estudiantes muy preparados y bien formados, muy respetuosos con la figura del licenciado y el doctor, cálidos y amables. Por eso me sentía muy bien y muy reconocido. México brindaba esa grandiosidad y generosidad.

\item \personaje{Ignacio} Esa es una gran tradición en México. México ha sido un gran receptor de personas latinoamericanas, o iberoamericanas. Precisamente de los exilios, por cuestiones económicas, políticas, ideológicas. Yo recuerdo aquí cuando vine la primera vez con Carmen Bueno, pues la figura de Ángel Palerm era relevante porque era un anarquista exiliado después de la República, por seguridad, porque obviamente lo matarían por la dictadura. Y que gracias a México pudo desarrollar toda la trayectoria que supuso tanto él como su esposa. Hoy día su hija todavía guarda el legado. Hay una escuela palermiana de antropología y tiene que ver con la grandeza de México que no tiene precisamente prejuicios en recibir. Este marzo ya llevo 10 años acá y también fue por una beca y de casualidad, en mi caso, la Secretaría de Relaciones Exteriores de México, pues tiene ese tipo de potencialidades para quien quiera venir a hacer una investigación.

\item \personaje{Davíd} Digamos que México en el campo de la antropología funcionaba como un país mucho más desarrollado que España, además de que, estructuralmente, el mercado de trabajo para un antropólogo era superior. Muy poca gente podía trabajar en España más allá de una Universidad o un Centro de Investigación, los antropólogos no teníamos muchas oportunidades, tal vez en alguna empresa en consultoría, pero había muy pocas oportunidades en España.

\item \personaje{Davíd} En cambio en México, había muchas más facilidades y oportunidades, entonces, por ejemplo, la Universidad de Hidalgo recibía muchos apoyos del PROMEP, programa de mejoramiento del profesorado. Te daban dinero para proyectos de investigación durante 2 años. Me apoyaron mucho y con eso pude publicar varias etnografías. Aprendí mucho de la antropología mexicana que siempre me ha parecido una antropología mucho más avanzada, que tiene más de 80 años. Los mexicanos habían desarrollado una tradición académica con conceptos muy sólidos, sin necesidad de acudir a los autores y conceptos de moda como si ocurría en España, con teorías muy bien testadas, con análisis empírico muy bien construido, es algo que siempre admiraba. ¿Cómo hacer una observación participante?¿Cómo describir una realidad? ?¿Cómo escribir una etnografía? El nivel, por ejemplo, de las de las tesis de licenciatura era un nivel tan alto, tan fuerte, equivalente a lo que podría ser aquí un máster o incluso hasta una tesis doctoral. Leí muchos trabajos de alumnos de licenciatura, de másetr y de doctorado absolutamente magníficos porque tuve una oportunidad de estar 2 años como evaluador en el premio INAH-Bernardino de Sahagún. Y algo que admiraba de los colegas mexicanos era precisamente esta tradición intelectual que tenían los mexicanos ante el hecho objetivo. Por eso muy poca influencia tuvo la antropología posmoderna en México porque no necesitaban recurrir a conceptos o ideas de moda importados por ambición o "para quedar bien", sino que ya tenían una tradición muy sólida. Y otra de las cosas que reconozco era la increíble capacidad de escribir etnografías. Leí maravillosas etnografías, de la primera a la última página, con rigor y método, muy bien construidas, si vieras tantos libros coordinados o editados con tanta calidad. Y revistas mexicanas que no están en los índices de alto impacto pero que tienen una calidad muy contrastada con artículos muy potentes y me sorprende mucho todo esto. Todavía me enorgullece enormemente porque también me marcó y fue una influencia muy fuerte para mí. Esta tradición académica influyó mucho en mi trayectoria. De hecho, lo primero que hice fue dedicarme a estudiar un grupo indígena, porque los pueblos originarios son parte de la identidad del país. Yo quise dedicar mi primer estudio a un pueblo originario en Hidalgo, un poco emulando a esos grandes maestros de la antropología en México que conocí en seminarios, en congresos, en cursos y en conferencias, y a los cuales asistía admirado. Y yo quise hacer antropología como ellos, como los antropólogos mexicanos. Obviamente, soy consciente y estoy de acuerdo con Lourdes Arizpe sobre este énfasis en el estudio de pueblos originarios en detrimento de otras cuestiones de la cultura y la sociedad mexicana como algo anómalo.

\item \personaje{Ignacio} ¿Cuántos años estuviste trabajando y viviendo en México?

\item \personaje{Davíd} Estuve del 2000 al 2010; me incorporé a la Universidad de Hidalgo a mediados de 2000, pero en el 2002 ya empecé a dar clases en la Escuela Nacional de Antropología e Historia (ENAH). Fui profesor en la licenciatura en etnología y en el máster. Estuve trabajando en la ENAH y acabé ganando una plaza permanente en el año 2010, la plaza que había quedado vacante por la inestimable pérdida de Margarita Nolasco, una de los siete magníficos de la antropología. Salió a concurso y la gané. Entonces, me incorporé al postgrado de antropología social en la ENAH y he de decir que ese fue tal vez el proceso de concurso más objetivo en el cual participé porque estuve varios años intentando participar en otros concursos de plazas y que no cuajaron por motivos muy variopintos y muy castizos. Básicamente, no tenía éxito porque no sabían quién era o porque tenía que competir con el "tapado" o el recomendado. Me sentí decepcionado y me di cuenta de cuán importante es tener buenas redes y contactos. Y que es ingenuo pensar que el mérito y la capacidad son decisivos. Entendí por qué David Harvey dijo que la Universidad no funciona peor que una empresa… pero tampoco mejor. Pero seguí adelante con la confianza que llegaría el momento, mi oportunidad. Ahora lo puedo contar y varias instituiones que habían publicado las convocatorias de concurso de plazas ni siquiera te contestaban a tu solicitud. Recuerdo que fue así en CIESAS, la Iberoamericana y otras más. Pero nunca me rendí. Al día siguiente de esta situación extraña ya estaba preparado para seguir presentándome. Y fue en el concurso de la plaza de la ENAH que sentí por primera vez que hubo un trato justo y un proceso objetivo porque vino a evaluarme un tribunal externo. También me evaluaban los propios alumnos, tenías que hacer una clase frente a alumnos. Me pareció un proceso objetivo, transparente, muy equitativo. Y al final acabé ganando la plaza en el posgrado de antropología de la ENAH. Un muy buen puesto en la mejor escuela de antropológos de América Latina.

\item \personaje{Ignacio} Y un año después de ganar la plaza, te vas…

\item \personaje{Davíd} Puede parecer sorprendente. pero lo más importante en aquel momento eran mis hijas y mi familia. El trabajo para mí es secundario, también a día de hoy. Una vez obtuve la plaza y después de un periodo de seis meses me convertí en funcionario de la ENAH-INAH, es decir, del Estado, con contrato de por vida. Y decido renunciar. Había llegado a la cumbre, a mi gran objetivo en la vida, en uno de los mejores lugares del mundo. Me había naturalizado como mexicano y no pensaba volver a España. Renuncié a mi plaza por amor a mis hijas. La situación del país se estaba poniendo complicada con la violencia y la inseguridad, y me hice la pregunta: ¿este país es vivible para mis hijas? La respuesta fue que no y concursé para una plaza de ayudante doctor, una categoría más baja y sin definitividad, en la Universidad de Sevilla, en cuyo proceso también tuve que competir con el "candidato de la casa".

\item \personaje{Davíd} Fueron cuestiones personales y familiares porque mis niñas estaban pequeñas, y decidimos irnos toda la familia a España. Laboralmente bajé como dos escalones, fue un paso atrás porque de tener una plaza de profesor de planta me vine aquí con una plaza temporal de profesor ayudante doctor. Una de las cosas que me enseñaron los Gitanos y esto es una de las cosas que en antropología ignoramos es la influencia que tienen las personas con las cuales convivimos en la propia personalidad del antropólogo. El conocimiento de los antropólogos con otras comunidades, con otras gentes diferentes a ti, se incorpora dentro de ti. Esa experiencia de campo es clave porque podemos decir que la etnografía es un experimento de experiencia, como dice Leonardo Piasere, se incorpora. Por ejemplo el concepto que familia que tengo está muy influido por los grupos humanos con los que convivido varios años.

\item \personaje{Davíd} La idea que tengo de la justicia, también está muy influida por todas esas gentes con las cuales conviví. Y justamente los Gitanos me enseñaron que lo más importante en la vida es la familia, el valor de la palabra, la amistad, la reciprocidad. Mis mejores amigos son Gitanos. Y yo renuncié a un puesto de trabajo fabuloso. Mis colegas no se lo podían entender. ¿Por qué renuncias? Es un trabajo de por vida, es un trabajo bien pagado ¡funcionario del Estado!.

\item \personaje{Davíd} Puse la primera familia en primer lugar, quería que mis hijas tuvieran el lugar para criarse, no digo que México no lo sea, pero en aquel momento surgió esa posibilidad, y dije bueno, pues que mis hijas vivan allá, en Sevilla, hay buen clima y una luz maravillosa. Estás cerca de todos los países en Europa, muy cerquita, también de mi familia en Madrid y Barcelona.

\item \personaje{Davíd} Esta decisión es el resultado de las influencias que también, de este conocimiento adquirido por impregnación, como dice Leonardo Piasere, es un conocimiento donde te vas impregnando y luego eso se va incorporando también a tú a tú *habitus*.

\item \personaje{Ignacio} Por eso también los antropólogos, somos un poquito raros ¿no? Lo hablaba con Eduardo Restrepo precisamente quien defiende la antropología como pura interacción social. Y ninguna interacción social te deja sin marca. Y en el momento en que conecta con algo eso de que hablas de impregnación es la misma idea de cuando vives en otros países, cuando te relacionas con otras comunidades, asumes elementos y los articulas e incluso te apropias ellos. Como bien dices y de repente llegas a Sevilla vuelves otra vez a España, pero muy diferente. O sea, no tienen nada que ver Andalucía y Cataluña, o sea sí tiene que ver, pero las diferencias son muy, muy palpables.

\item \personaje{Davíd} Sí, desde que salí de Cataluña en el año 2000 siempre me he sentido y he sido tratado como un foráneo, como señalaba. Llegué a la Universidad de Hidalgo como forastero, llegué a la ENAH también, aunque ya me había naturalizado como mexicano. Y llegué a Sevilla como catalán, un catalán en Sevilla, lo cual, pues también es una anomalía que no se te espera, no se te espera en la ENAH, no se te espera en Hidalgo, no se te espera en Sevilla. Eso es la dislocación que es algo muy típico de la globalización pues yo la he sentido, esa idea de que no estás, ya nunca vas a poder estar en el lugar donde te criaste como antes hablábamos de la infancia. En la ENAH me acogieron estupendamente y en la Hidalgo también. En la ENAH tenía un despacho muy reducido de 3 m2, nada más, de un cubículo compartido con 3 profesores. Pero en la ENAH compartía despacho con una etnohistoriadora, en la puerta de al lado había un arqueólogo, en frente tenía un lingüista, y también un antropólogo físico. Esto es lo de Claudio Esteva, la interdisciplina, las cuatro ramas de la antropología, que ya ha desaparecido en España.

\item \personaje{Ignacio} Claro, las ramas que componen la antropología también dependen muchísimo de los países.

\item \personaje{Davíd} Qué bueno que comentas esto porque efectivamente en Sevilla me encontré frente a una herencia de un enfoque antropológico muy centrado en la tradición y la identidad en relación al pueblo andaluz. No lo juzgo, pero lo que me sorprendió era el valor folclorizante de la identidad. Sentir que como andluz tú eres de aquí y no eres de allí, lo cual es un concepto que se desarma por sí mismo. Es decir, que si "yo soy de aquí" porque como tapas y bailo flamenco o "soy andaluz" porque cargo a la virgen en un paso de Semana Santa, todo ello dejaba fuera el aparataje, las políticas de los lugares. Porque en cualquier lugar hay múltiples voces. Y como parece que el lugar natural es la identidad pues ante eso cabe rebelarse. Y te percatas que con mayor motivo en Sevilla la cultura está unida a la religión. Y yo como ateo observo esta unión. Y es obvio que es un fenómeno recurrente y cumple una función. Después de vivir en Barcelona, Paris, Ciudad de México, con una amplia oferta cultural, museos, dinamismos ciudadanos, y te tienes que adaptar a una realidad marcada por esta tradición, opuesta a la aconfesionalidad del Estado, incluso en la propia institución donde trabajas. Y una ciudad como Sevilla que está muy apegada a lo propio, a sus tradiciones, a la religión, a las redes que establecen las hermandades, donde es muy difícil hacer amigos, donde te tienes que proteger de los chismes, pero que también tiene sus componentes positivos. No me parece ni mejor ni peor, sino una ciudad diferente. Ten en cuenta que los antropólogos vemos que la realidad esconde otras cosas y los demás son un espejo en el que me ven, siempre deforme, que nunca nos dice la verdad. El verdadero mundo está detrás del espejo, de la máscara. Y la gente llora y ríe cuando se quita la máscara. Y todo ello es parte de un sistema cultural. Y para entender bien eso hay que gestionar bien las preguntas puesto que no es una cuestión solo de afirmaciones.

En la Universidad de Hidalgo, ahí lo que dominaba era un fuerte sentimiento provinciano. Y ellos se sentían muy orgullosos de ser hidalguenses. Pasados unos años escribí un artículo sobre caciquismo en Hidalgo que me costó mucho publicar en México, las revistas me devolvían el manuscrito sin haberlo evaluado. Les resultaba incómodo publicar algo sobre caciquismo en la universidad un tema que se ignora.

La ENAH era una institución más global, tenía una perspectiva más de izquierdas y te abría las puertas a un nuevo conocimiento. Había esta transversalidad, esta mezcla también de generaciones académicas, colegas de otra generación anterior pero también gente joven muy preparada, lo cual era un valor muy preciado en la ENAH. A la vez que también fuertes divisiones y faccionalismo que destruyen también una institución. Es obvio que esta es una de nuestras miserias en la Universidad, el faccionalismo y la lógica segmentaria. En los departamentos universitarios nos organizamos como tribu, somos como los Nuer; divididos en facciones, clanes y cliques, por decirlo suavemente. Los clanes en los departamentos universitarios son muy interesantes de observar. Un clan en una institución tiene dos funciones: una, compartir información. Ves a sus miembros cómo hablan entre ellos en el pasillo, en una esquina, en la cafetería, y pasas junto a ellos y bajan la voz. Dos, tiene una función de protección, se defienden unos a otros cuando algún miembro se ve atacado. O votan lo mismo en las asambleas de los Departamentos como voto grupal, independientemente del acuerdo, solo por protegerse unos a otros. Y el tema de los catedráticos… cuando te integras por primera vez en un grupo de investigación te sientes como el joven chimpancé. ¿Y cómo ejerce el control el macho alfa de la manada? De dos maneras: una, te trata con mucho respecto "el doctor Lagunas por aquí, el doctor Lagunas por allá, ha publicado este libro, tiene este proyecto…"; la otra, de vez en cuando te da un plátano: te da dinero para que hagas un viaje o a un congreso, para publicaciones. Es un ejercicio de poder, control y de disciplinación. 

Entonces, sí, evidentemente me encontré con estos dilemas. Pero Sevilla es un Departamento muy potente, Barcelona, Madrid, Sevilla, El País Vasco son, digamos, los grandes núcleos de la antropología en España, Granada también.

\item \personaje{Davíd} Pero tal vez me iría ahora mismo otra vez a México, o sea, ahora mismo si me dicen "te vas a la UNAM, a la UAM o al CIESAS". No lo sé, no lo descarto. En la Universidad de Sevilla estoy muy contento. Tengo unos compañeros muy competentes, aprendo mucho de ellos, con una visión muy interesante, complementaria. Al final he acabado siendo secretario y después Director del Departamento, no sé por qué, tal vez porque ya me tocaba. En Hidalgo también fui Director del Departamento, no sé lo que la gente vería en mí, tal vez caigo simpático, o no sé, tengo buen corazón como decían los Gitanos. O tal vez, me gusta trabajar con equipos y debes tener las ideas muy claras. Tal vez noto la influencia de mi padre quien fue más conocido por haber sido entrenador nacional de equipos de fútbol como el Girona o el Andorra. Mi padre tenía que trabajar mucho con los jugadores, con el grupo, cohesionarlo, motivarlo, que dé lo mejor de sí cada individsuo. Y la Dirección es una buena oportunidad también de desarrollar tu trabajo en la gestión que es otro de los trabajos que tenemos que hacer aunque aparentemente sea menos gratificante que la docencia o la investigación. Tú sabes bien que nos dedicamos a la docencia y a la investigación, y a unos les gusta más la docencia y a otros les gusta más la investigación, que son casi siempre actividades muy gratificantes. Pero tenemos una tercera tarea que tú conoces muy bien y que además eres muy bueno en eso. Qué es la gestión y que a veces no es tan gratificante, pero hay que hacerlo porque sencillamente sientes que hay que hacerlo, tener una vocación de servicio a los demás.

\item \personaje{Davíd} Esta idea de que no eres tú el que elige, sino que son los demás que te dicen "David, tienes que ser nuestro líder". Es la idea del hecichero, del contrato social con el hechicero y su magia, que señalaba Lévi-Straus. Supongo que es el grupo el que ve en alguien ese algo, la función simbólica y la epopeya de Quesalid, ese chamán inmortalizado por Lévi-Strauss que no creía en los chamanes pero. al igual que en La vida de Brian, gracias a que hay una sociedad que confía en él deja atrás su escepticismo y se convierte en el chamán de la tribu.

\item \personaje{Ignacio} Y ahora, por ejemplo. De hecho, cuando estuviste de visita en la Universidad Autónoma Metropolitana en Lerma presentaste resultados de un proyecto europeo en el que estás trabajando. Precisamente la cuestión de las comunidades gitanas en diferentes partes de Europa y que está ocurriendo con las migraciones del este de familias. Cómo ves ahora mismo desde tu posición muy subjetiva, muy personal. ¿Cómo ves la antropología en estos tiempos tan digitales, abstractos, de inteligencia artificial, de algoritmos?

\item \personaje{Davíd} Esa antropología, la edad de oro de la antropología de los años cincuenta que se seguía enseñando en nuestras facultades, ya no tiene tanto sentido. Coincido con Luis Reygadas sobre que ahora tal vez lo que debemos hacer es adaptarnos un poco a esas realidades, tomar las bases de esa buena tradición crítica que tenemos, de cómo analizar teórica y metodológicamente un problema, cualquier problema social. Y dar pie también a abrir otras líneas, aquí por ejemplo en Sevilla, cuesta mucho abrir alguna línea dedicada a la antropología aplicada o a la antropología de la empresa, precisamente por esos esquemas que tenemos tradicionales de la antropología, de la edad de oro de los años 50, del estructuralismo, del simbolismo, de todas estas tradiciones. Estoy de acuerdo con Claudio Lomnitz de que ha habido en México en los últimos años un período de confusión, de no saber bien qué hacer. Una vez que ya el papel tradicional del antropólogo, vinculado al indigenismo, acabó implosionando, y toda la crítica ya desde los años 70 a este tipo de antropología aplicada de cómo el indio tendría que ser transformado, dio pie a otra realidad. Esto lo explica Claudio Lomnitz, es el tercer momento de la antropología en México, que es el momento del estudio de una realidad cambiante, una sociedad de consumo donde la vida humana aparece dominada por el mercado, donde se trata de construir la ciudadanía, la ciudadanía política y la importancia de lo público, también de las políticas públicas. Me siento hoy más afín a la antropología pública tal como plantea Sam Beck. Entonces yo pienso que el libro que hemos publicado Gitanos rumanos en España de 2021 que hemos desarrollado sobre migración de poblaciones gitanas en España es un trabajo con un objetivo: aportar evidencias y evaluar las políticas públicas sobre los Gitanos rumanos y cómo repdoucen la pobreza. Este es un filón, la evaluación de políticas públicas, que en México ya se está desarrollando desde hace años. Estoy pensando, sobre todo, en el CIESAS, que tiene mucha vinculación con proyectos de gobierno y creo que es un centro de investigación magnífico, también la UAM, obviamente la UNAM. Pero CIESAS, por ejemplo, ha trabajado mucho y son oportunidades. Es un nicho de oportunidad muy interesante. También el estudio de los medios de comunicación: prensa, radio, televisión. En la UAM estos estudios urbanos son muy interesantes, muy potentes.

\item \personaje{Davíd} El turismo, que es otro nicho importantísimo, por ejemplo, cuando se construyó Cancún ahí no había ningún antropólogo. Y ahora con el tema del tren maya, pues vas a ver antropólogos allí para que nos expliquen qué está ocurriendo. El tema de salud, por ejemplo, es fundamental para la antropología. Y una de las cosas que los antropólogos podemos aportar es realizar diagnósticos, un buen diagnóstico, por ejemplo, el caso de Cancún en los años 70. Ese hubiera sido un buen diagnóstico. Entonces desplazar un poco el foco, sin renunciar a esa tradición crítica a estos nuevos nichos de oportunidad y replantear un poco también los planes de estudio, los sistemas de trabajo más interdisciplinares.

\item \personaje{Davíd} Yo creo que también en las universidades. Creo que el conocimiento que les estamos dando, pues a veces es muy parcial, nada metódico, son conocimientos densos, pero que no atienden muchas de las cuestiones sociales. Y a muchos de mis alumnos les digo "quiero que me hagáis un trabajo sobre algún problema relacionado con vuestra experiencia cercana, sobre vuestro barrio, sobre tu comunidad de vecinos, sobre el estado de la calle, sobre los coches o el tráfico, sobre la contaminación, sobre la violencia, sobre el botellón o el problema de la vivienda". Estas cuestiones que son los que las que preocupan a la ciudadanía".

\item \personaje{Ignacio} ¿Entonces, si ese es nuestro presente, hacia dónde va el futuro de la antropología?

\item \personaje{Davíd} Bueno, yo lo que veo es que… Primero, es que ha habido como una hiper especialización del conocimiento, es decir que ahora tenemos toda una antropología del turismo, dentro de la antropología del turismo tenemos especializaciones y subespecializaciones a su vez. Y así con otros temas y problemas. Entonces esta idea a mí me crea cierta incomodidad epistemológica por el hecho de que se busca siempre la especialización y de hecho no sé decir cuándo hablamos de interdisciplinariedad cuando en realidad estamos buscando la subespecialización de otra disciplina. Entonces algunos comprueban que hay valor en el conocimiento antropológico que también tiene un espacio para los autores clásicos, para ese idioma común que hemos ido perdiendo, hemos ido perdiendo ese idioma común y ahora tenemos tantas especializaciones que ya no recurrimos a la tradición crítica, solidaria, académica, ideológicamente. Todo eso lo explica muy bien Ignasi Terradas de quien tomo prestadas estas ideas. Entonces veo que hay mucho narcisismo dentro de la antropología, ya no es una antropología egocéntrica, sino narcisista, como decía Claudio Esteva, fíjate en México cuando lo entrevisté al Dr. Esteva en 2009 y me decía. "yo ahora voy a España y veo los antropólogos y veo a un Narciso". Qué guapo soy, qué inteligente soy, y al final se acaba ahogando. Entonces solos no vamos a poder ver nada, entonces creo que es muy interesante eso, pues acudir a la tradición, a nuestra tradición, pero también a otras a otras disciplinas que también nos pueden ayudar. Y, por ejemplo, veo cosas muy interesantes, por ejemplo, el tema de la antropología jurídica en España, que es muy minoritario, pero este acercamiento que hay por el propio Ignasi Tarradas, trabaja mucho con juristas. Pero Terradas tiene que hacer ese trabajo sobre todo fuera de España, porque aquí no hay muchos y trabaja mucho con juristas italianos que están interesados en la antropología y el derecho. Eso me parece que son hacia donde podemos ir trabajando y también trabajando mucho en un tema que es el tema de las escuelas, es un tema fundamental donde yo estoy por escribir algo, sobre la enseñanza de la historia en secundaria, en bachillerato, no sé, a mis hijas les están enseñando auténticas tonterías en la historia, y yo les digo a ellas que no hagan mucho caso de lo que les dice la profesora. Entonces creo que necesitamos ahí también que los antropólogos abramos un espacio dentro también de la educación, para, por ejemplo, incorporar en el currículum educativo el tema de la diversidad cultural que es fundamental para combatir el racismo, las desigualdades.

\item \personaje{Ignacio} Pues muchísimas gracias, David por tu tiempo, por tus reflexiones, por tu experiencia de vida que has compartido. Y si por ahí está la antropología, ¿cómo estará la vida dentro de 20 años?

\item \personaje{Davíd} Bueno, pues yo estaré en México probablemente. Yo pienso volver a México porque es mi patria también. Yo amo México, amo sus gentes, amo su cultura, amo su comida, amo muchas cosas de este país y dentro de mí lo digo, orgullosamente, que soy culturalmente mestizo. Soy un poquito de catalán, un poquito de mexicano, ahora un poquito de Sevillano.

\item \personaje{Ignacio} Como la canción "No soy de aquí ni soy de allá, no tengo edad ni porvenir y felicidades…"

\item \personaje{Davíd} Claro, entonces y yo dentro de 20 años, tal vez me veo en México.

\item \personaje{Ignacio} Pues donde sea que estés que te veas bien es lo importante. Muchísimas gracias.

\item \personaje{Davíd} Gracias, Nacho.

\end{transcripcion}