---
type: chapter
subtitle: ""
lang: es
pdf-engine: xelatex
---

\vspace{-\baselineskip}

# Observando al Estado y como el Estado. Presentación {.unnumbered}

\addtocontents{toc}{\protect\hspace{1.5em}Abraham Zaíd Díaz Delgado\par}

Las políticas públicas (PP) repercuten en nuestras vidas, pues suponen el funcionamiento de los engranajes políticos que los Estados nacionales ponen en marcha para dar solución a circunstancias identificadas como problemáticas dentro del orden social vigente. No es casualidad que su estudio se centre en comprender qué hacen los gobiernos para que la maquinaria opere tal como lo hace, con sus fallas ineludibles y sus puntos perfectibles. Asimismo, permiten reflexionar en profundidad sobre las razones que dan origen al orden dispuesto de los engranajes de la maquinaria gubernamental, cuestionándose ¿por qué las piezas se encuentran en esa posición y no en otra?, ¿cómo debe resolverse determinado problema?, ¿qué tuvo que suceder para que una realidad fuera reconocida como un problema que solo el Estado puede resolver? Y, sobre todo, ¿por qué en muchas ocasiones no logra darle solución? De este modo, continúan surgiendo interrogantes sobre los efectos que las potenciales soluciones tienen en realidad, dado que las políticas públicas son, en esencia, una compleja matriz de toma de decisiones humanas guiadas por el imperativo ideológico que reivindica la legitimidad del Estado y de sus instituciones. Bajo este enfoque, resulta necesario indagar, en un nivel empírico, en la experiencia de los diversos agentes que participan en el complejo entramado de fuerzas políticas que conforman las políticas públicas. Este libro titulado “Políticas Públicas y Etnografía. Observado al Estado y como el Estado” tiene como objetivo adentrarse en los mundos de significados autocontenidos en el universo de las políticas públicas valorando la diversidad de voces, posiciones y experiencias en la atención de problemáticas sociales particulares, por lo tanto, he de advertir a los lectores que este no es un compilado de desarrollo riguroso de los marcos teóricos hegemónicos en el estudio de las PP, más bien encontrará un cúmulo de experiencias que, aunque distantes espacial y temporalmente, coinciden con la necesidad de someter a debate las implicaciones personales, afectivas y profesionales que interpelan a diversos investigadores sociales en su vinculación con las PP. Este libro tiene como propósito abrir un espacio para el debate científico que recoja la reflexión crítica en torno a la experiencia de quienes, en calidad de investigadores sociales, participan en alguna fase del ciclo de las políticas públicas (PP). Esta perspectiva se funda en el reconocimiento de un nivel de análisis que ha sido poco explorado hasta la actualidad, cuya relevancia académica y operativa encierra un potencial significativo que solo se revela plenamente cuando la práctica se sostiene en el tiempo, se cuestiona y comparte para ser sometido a un debate productivo. En este sentido, las experiencias etnográficas que aquí se presentan constituyen fuentes valiosas para dar continuidad a un aprendizaje colectivo, siendo capaces de atenuar la atomización de los esfuerzos investigativos y de replantear la visión común que considera los resultados del estudio de las PP como procesos distantes, fríos, impersonales y estériles.

Los trabajos de investigación reunidos en este libro constituyen una selección de material idóneo para la identificación de casos de referencia que permitirán realizar estudios de política comparada, con el agregado de que en ellos se ofrecen las descripciones densas elaboradas por los autores que, en la mayoría de los casos, ocuparon posiciones privilegiadas desde las cuales lograron reconocer tanto las virtudes como las áreas de oportunidad en el abordaje de los problemas sociales contemporáneos a través de políticas públicas específicas.

En el primer capítulo, Abraham Zaíd Díaz Delgado revisita etnográficamente su experiencia profesional en la dependencia operadora de la política de telecomunicaciones en México durante los años 2024 y 2025, mostrando que, en el seno de las políticas públicas (PP), se debaten y definen distintas perspectivas de la idea hegemónica del Estado, así como del discurso gubernamental de la llamada “Cuarta Transformación” (4T), en este caso particular. Destaca que la política de telecomunicaciones funge como punto de encuentro entre el desarrollo tecnológico y la consolidación de un régimen político. En lo que toca a los retos de la PP del sector, se reconoce la necesidad de superar la contradicción entre el discurso de justicia social de la 4T y la complejidad real que esta implica, así como el hecho de que la política de telecomunicaciones es reflejo de dicha inconsistencia. Además, señala que la superación de la brecha digital está atravesada por sesgos de carácter técnico que no son necesariamente vinculantes con la dignificación de los medios de vida de las poblaciones incomunicadas. Otro aspecto que remarca este trabajo es que la brecha digital reproduce brechas sociales de clase, lo que la convierte en un fenómeno predominantemente político. Asimismo, el texto ilustra la coyuntura política del cambio institucional en México con la llegada al poder del partido MORENA, proceso que ha generado contradicciones y desaciertos en la operación de las PP. Pero, principalmente, abre un panorama novedoso sobre el potencial explicativo de la etnografía para el ciclo de las políticas públicas, no solo como un método de extracción de información para su diagnóstico, implementación y evaluación, sino también como una herramienta aplicada a los mecanismos internos y a los andares cotidianos que involucran a funcionarios públicos, operadores de las PP y población beneficiaria, desde una lectura crítica de la antropología y etnografía política, del Estado, la ley y las instituciones, introduciendo una vía analítica no exenta de originalidad para las ciencias sociales y la función pública.

En el segundo capítulo Marco Rodríguez y Nancy Jiménez analizan el impacto de la política social del régimen de gobierno actual en México, autodenominado de “la cuarta transformación” (4T), en los trabajadores formales e informales del sector de residuos, específicamente en Acapulco (Guerrero), Oaxaca de Juárez (Oaxaca), Tlaxcala (Tlaxcala) y Cuetzalan (Puebla) con aquellos que cumplen las tareas de procesamiento, recolección, traslado y tratamiento de desechos sólidos. El estudio emplea un enfoque mixto que abona al diálogo entre la profundidad descriptiva con visión panorámica de los datos estadísticos e indicadores de evaluación a fin de proponer una alineación entre políticas públicas a diversas escalas y niveles de gobierno. La pertinencia de esta investigación radica en tomar como punto de partida el perfil socioeconómico de los trabajadores resultando que, debido a la condición marginal en la que suelen vivir, son objeto de múltiples programas de asistencia social, en un principio, porque la cobertura de manutención que otorga su remuneración como trabajadores del sector de residuos es insuficiente. Aunado a ello, la aplicación a formar parte de otros programas sociales acarrea una serie de obstáculos que deben sortear y que recrudecen la condición de vulnerabilidad en la que están sumergidas sus familias. Otra virtud del trabajo de los autores es reconocer la desigualdad como una condición sine qua non para determinadas políticas sociales y la recolección de datos en diversos contextos dentro del territorio mexicano demuestra que fungen también como mecanismos de diferenciación revitalizando diversas violencias, sobre todo la económica, de manera estructural. Con todo, la corrección que promueve el capítulo insta a alineamiento de multiescalar de la política social para dignificar la vida de los sectores marginados y puntualmente del sector laboral de la gestión de residuos sólidos.

El tercer capítulo autoría de Enver Vargas y David Alzate profundiza en el análisis crítico de categorías dominantes que fundan las bases sobre las cuales se diseña, implementa y evalúan las políticas públicas desde la valoración de la subjetividad y reflexividad en la investigación, dichas categorías se reflejan en la noción del Estado como ente unitario o monolítico, la legitimidad en el actuar gubernamental y la impersonalidad con que la burocracia asume a las personas, objetivándolas y despojándolas en la práctica de su calidad de sujetos de derecho cuando han de entrar en acción los fundamentos estatales para su protección como lo son las políticas públicas. Los autores de origen colombiano comparten las etnografías de dos casos concretos en su país para ello; el primero de ellos aborda la operación del Programa de Defensoría del Pueblo en un momento de emergencia humanitaria frente a las violaciones de derechos humanos perpetradas en el contexto de los años del conflicto armado por las guerrillas en aquel país y el segundo expone una red criminal en el Departamento Administrativo de Seguridad luego de encontrarse culpables a diversos funcionarios públicos que colaboraron en el despliegue criminal en ese mismo contexto. Es importante reconocer que ambos casos de estudio oscilan entre la “técnica y la política” a decir que los autores, dejando de manifiesto una posición parcial y pragmática necesaria para poder desarrollar una exploración etnográfica de mayor alcance y multivocal, esto es algo que constantemente ha de hacerse en casos de corrupción y violencia como los aquí atendidos. Por si fuera poco, hace presencia otro tipo de abordaje etnográfico conocido como “etnografía documental” que somete a cuestionamiento las estructuras que consolidan los archivos y documentos que soportan los relatos comúnmente hegemónicos de un momento histórico, por lo común, en entornos de riesgo y conflicto esta clase de etnografía es de gran utilidad; siendo este capítulo un claro ejemplo. En suma, Vargas y Alzate demuestran el borramiento y superación de las nociones de típicamente evocan la idea de Estado, sus procesos y políticas securitarias que, específicamente en Colombia se ven excedidos en la atención del trauma emanado del conflicto armado y porque ese daño se produjo, en parte, por el entrelazamiento entre estatalidad y criminalidad.

El capítulo cuatro coescrito por Omar Becerra, Tzitzi Becerra y Francisco Ayala se ocupa de analizar el estado vigente de las políticas públicas orientadas a la preservación y promoción de los patrimonios culturales del estado de Michoacán, México, alertando sobre la parcialidad de éstas y la necesidad de estrechar la vinculación con las comunidades por el desconocimiento de las necesidades culturales reales de la población incluyendo factores de orden económico, social y ambiental a las políticas públicas locales en torno al patrimonio cultural michoacano, afinando así el proceso de éstas y evitando su operación de manera aislada como mecanismo de gobierno. Además, se expone desde una perspectiva histórica el proceso institucional y legal que rige hasta el día de hoy el entorno político del patrimonio material e inmaterial con el que cuenta Michoacán, lejos de centrarse en un programa o bien cultural específico, los autores demuestran elementos contextuales sobre los cuales la etnografía se presenta como una alternativa viable para la mejora de las políticas públicas culturales, de las instituciones que las construyen y ejecutan, así como de la construcción discursiva de la riqueza cultural y patrimonial local. Finalmente, este capítulo colectivo sugiere que el aumento del financiamiento estatal para fortalecer las cadenas de valor existentes en materia cultural y, sobre todo, destaca la necesidad de involucrar a las comunidades objetivo en el establecimiento de una agenda cultural para un correcto diagnóstico e implementación de las políticas públicas culturales en Michoacán.

En el capítulo quinto Alejandro Agudo ilustra las complejidades que alberga la construcción de conocimiento y toma de decisiones en las posiciones de “antropólogo activista” y “antropólogo consultor” empleando dos ejemplos prácticos que contrastan las condiciones, directrices y demandas de cada escenario, si bien ambos contextos son distintos, en ellos coincide la etnografía como parte central de las funciones desarrolladas por el antropólogo y dan pie a cuestionamientos profundos sobre la posibilidad de conciliar entre el activismo y la consultoría orientados a la atención de poblaciones vulnerables. Asimismo, el autor advierte desde su experiencia acumulada que existen algunos riesgos y condicionamientos interpretativos involucrados en estos distintos entornos de aplicación y construcción del conocimiento, siendo quizá el más claro, la tendencia a caer en polos opuestos de la práctica etnográfica. Por un lado, señala que la adopción de una postura moral denunciante útil para evidenciar los legítimos reclamos por justicia de sectores marginados sistemáticamente puede llevar al punto de imposibilitar la visualización de soluciones de los problemas que les aquejan e incluso reforzando una visión parcial del origen de dichos problemas, así como obstaculizar el entendimiento de las formas en cómo funciona la realidad social más amplia, lo que derivaría un diagnóstico sesgado y limitante de la vulnerabilidad referida. Por otra parte, aborda empíricamente la incidencia de agendas políticas externas a las instituciones, dependencias, organismos y demás instancias encargadas de llevar a cabo proyectos de consultoría que tienen a como prioridad idear, articular, promover y emprender soluciones a problemas puntuales para determinados sectores, mismas que derivan en procedimientos y tratamientos de información que tiende a homogenizar los resultados en informes, recomendaciones o archivos que desdibujan la profundidad reflexiva de la etnografía y que pocas veces se basan realmente en las reflexiones derivadas de ésta, uno de los factores transversales a estas agendas es el tiempo, puesto que la etnografía deviene necesariamente en una honda reflexión que lleva tiempo procesar y expresar en los términos adecuados para su aplicación en contextos donde potencialmente podría incidir. Finalmente, este capítulo cumple con uno de los fines esenciales de este libro al poner en debate las contradicciones y tensiones éticas que se han definido típicamente unos espacios como académicos y otros como aplicados casi exclusivamente.

Virginia Ramírez presenta en el sexto capítulo los efectos que ha tenido el levantamiento del muro fronterizo de los Estados Unidos para marcar la división con el territorio mexicano en una colonia marginal de Tijuana (Baja California) generando la reconfiguración del paisaje urbano a través del desalojo y despojo de viviendas para construir vialidades que agilicen la movilidad en esa ciudad. El capítulo de la antropóloga va más allá de las políticas públicas como medio de acción de un estado nacional, ya que el contexto de la frontera norte de México se ve influido por la actual crisis de movilidad humana a escala global, siendo la ciudad referida en esta etnografía donde se da el flujo de migrantes más numeroso de todo el mundo. La investigación se inscribe en el contexto del programa federal “Viaducto Elevado Tijuana”, un megaproyecto de infraestructura emprendido por el Estado mexicano para dar abasto a la movilidad de la zona y que no solo ha generado cambios en la concepción del espacio público, sino que ha devenido en un punto de quiebre de las historias de vida de los habitantes de la colonia Libertad. El capítulo también muestra la yuxtaposición de políticas públicas que no se encuentran alineadas dada la preeminencia de agendas que obedecen a intereses políticos, factores económicos y a la gestión de crisis que desplazan y criminalizan familias además de precarizar las condiciones de vida locales. Este caso particular hace gala de la influencia que el gobierno estadounidense ejerce directa o indirectamente en la política pública nacional en temas migratorios, profundizando la identidad de Tijuana como una ciudad de paso e indigno para la residencia. Adicionalmente, refleja que la vida de los afectados por la construcción del viaducto ya se encontraba atravesada por distintas violencias, lo que posibilitó designarlos como objetos descartables para el desarrollo del megaproyecto, la falta de oportunidades es un problema de larga data en donde el trabajo de los “polleros” se hizo popular hasta el día de hoy en el que ha sido cooptado por grupos delincuenciales por los que impera la violencia en la zona y hace (en algunos casos) que el desalojo promovido desde el gobierno resulte en una opción razonable para conservar la vida. Metodológicamente este capítulo tiene la virtud de emplear la etnografía como hoja de ruta para conciliar y resolver problemas operativos sobre la marcha del proyecto del viaducto, buscando colocar en primer plano a las personas desalojadas e interesándose por los dilemas inherentes al cambio que el proyecto generó en sus vidas.

Por su parte, el séptimo capítulo escrito por Edgar Flores expone como la relación entre las prácticas sociales que permiten a las personas apropiarse e identificarse con el paisaje urbano pueden dar sentido al emprendimiento de políticas públicas destinadas al mejoramiento de las condiciones de vida de zonas periféricas de la Zona Metropolitana del Valle de México, a partir de la observación de la cotidianidad en áreas públicas de recreación y esparcimiento como parques, plazas públicas y complejos deportivos en el municipio de Ixtapaluca, Estado de México. Pese a que las reflexiones no van orientadas a un programa o política pública locas concreta, el autor busca que con la apertura y flexibilidad que permite la etnografía se pueda trazar un puente que vincule la experiencia habitual del espacio urbano con la toma de decisiones a distintos niveles y órdenes gubernamentales. Cabe destacar que el esfuerzo investigativo del etnógrafo ha decantado por apelar a la objetividad y neutralidad para hacer esto posible, y con ello paliar la tensión entre la complejidad y reflexión profunda para atender al pragmatismo que muchas veces se le atribuye a los ciclos de la política pública, a bien de dialogar entre ambas perspectivas y aminorar el caos que la descripción densa de las situaciones cotidianas en los espacios recreativos y los procesos micropolíticos de la toma de decisiones pueden atraer. El autor también destaca la capacidad de la antropología urbana para contribuir en el diseño de espacios públicos que coadyuven al bienestar de las poblaciones circundantes dado que los espacios pueden ser comprendidos como procesos socioculturales y políticos en sí mismos en los cuales están insertados múltiples actores rompiendo con la dicotomía tradicional entre sociedad y Estado. Finalmente, a partir de la observación flotante se relatan las necesidades y utilidad que las personas hacen de estos entornos comunes valorando el trabajo etnográfico (y en general académico) como un elemento necesario y vinculante dentro de las políticas públicas del espacio público.

En el capítulo ocho Julio Rodríguez da cuenta de múltiples áreas de oportunidad en la atención pública que se brinda a adultos mayores en situación de calle, pese a contar con funcionarios que manifiestan vocación de servicio, las condicionantes estructurales de los programas de asistencia a este sector se ven entorpecidos por limitantes burocráticas y por la falta de disposición de recursos adecuados y suficientes para cubrir con suficiencia las necesidades de este sector. El texto se enfoca en presentar un análisis del trabajo desarrollado en dos instancias públicas: DIF e INAPAM dentro del municipio de Naucalpan de Juárez (Estado de México). Recientemente, en el contexto mexicano se han promovido diversos programas de política social dirigidos a beneficiar a la población de la tercera edad a través de inventivos económicos y provisión de servicios básicos, sin embargo, estos esfuerzos han sido estériles para contrarrestar la vulnerabilidad de este grupo de edad como advierte el autor, su lectura crítica de estas políticas develan que hacen parte de las bases de fundan la desigualdad y exclusión de manera estructural, por lo que insistir en la formulación de ambientes propicios para vivir una vejez digna es una tarea impostergable para el Estado mexicano y en ella habrán de considerarse variables más allá de la materialidad, dado que el bienestar es una noción volátil que está en función del contexto histórico. La situación de calle en adultos mayores es una realidad comúnmente ignorada u omitida en la prescripción de políticas públicas de asistencia social, excluyendo aún más a esas personas de alternativas de vida digna; además los programas sociales emblemáticos del régimen actual en el país demandan la superación de filtros burocráticos que no contemplan esas realidades menesterosas y que la poca flexibilidad en sus procesos de incorporación imposibilitan la debida atención a los más desfavorecidos perpetuando la exclusión extrema.

El capítulo nueve, escrito por Laura Matamala se distingue por ir a las bases morales del bienestar entendido desde el ejercicio de la caridad y el humanitarismo en un albergue para enfermos y una casa hogar para niños, ambos ejemplos someten a debate el carácter político de las redes interinstitucionales de beneficencia que se proponen paliar los problemas que emergen en poblaciones vulnerables ante la imposibilidad estatal de proveer la cobertura de sus necesidades básicas. La autora echa mano de un prolongado recorrido por instituciones de cuidado con fundamentos religiosos para articular una autoetnografía que desencadena profundas reflexiones sobre el entrelazamiento real entre el Estado y la Iglesia hasta nuestros días, así como las funciones que cubren y, además, expone el desbordamiento de las categorías predominantes en el estudio los activismos y las labores de asistencia humanitaria desde las ciencias sociales y humanidades. El valor la autoetnografía que compone este trabajo exhibe también una serie de dilemas éticos, morales y prácticos en la dicotomía entre investigación y activismo, develando que la toma de decisiones a niveles operativos y gubernamentales demanda adherirse a una postura siempre perfectible, por ejemplo, con la participación de las organizaciones que proveen servicios humanitarios en redes o como depositario de donaciones que permiten su funcionamiento, pero que sin embargo, no son sometidas a mecanismos rigurosos de transparencia como lo harían agencias del sector público. Con todo y que el trabajo no aborda de manera directa la relación de la autora con un programa o plan de política pública el análisis de su propia experiencia en los espacios de atención humanitaria evidencian que, al igual que la política pública, las motivaciones e ideales suelen establecerse en alusión a una población objetivo mucho más imaginada que real que homogeniza y esencializa a los sujetos beneficiarios como receptáculos de las acciones institucionales lo que reduce la visión y descarta su potencial de agenciamiento que, sin embargo, existe y que les hace emprender diversas estrategias en pro de maximizar los recursos obtenidos bajo su condición de vulnerabilidad.

Finalmente, el Comité Editorial de la División de Ciencias Sociales y Humanidades de la Universidad Autónoma Metropolitana, Unidad Lerma, y la coordinación del libro “Políticas Públicas y Etnografía. Observado al Estado y como el Estado” expresamos nuestro más profundo agradecimiento a los autores que han nutrido este espacio con trabajos de investigación de alta calidad y relevancia para nuestra actualidad. Asimismo, reconocemos a los dictaminadores anónimos de cada contribución, quienes participaron en el proceso de revisión por pares ciegos, procurando la calidad académica de este número y compartiendo generosamente parte de su tiempo y conocimiento de manera voluntaria. Finalmente, se invita a los lectores a fomentar el debate alrededor de este nicho de investigación emergente pero fecundo donde confluyen las tensiones, paradojas y contradicciones propias de las políticas públicas y la etnografía, las cuales merecen ser objeto de estudio y reflexión.

\begin{flushright}
\Large Abraham Zaíd Díaz Delgado\\

\Large \textit{Coordinador}
\end{flushright}
